### DISCUSSION TITLE
Duplicated entries in generated SPDX

### DISCUSSION THREAD

**Discussion by dgutson** [oss-review-toolkit/ort#6700] [Q&A]
I found duplicates in the generated SPDX:
```yaml
- SPDXID: "SPDXRef-Package-NPM-webassemblyjs-wast-parser-1.9.0"
  copyrightText: "Copyright (c) 2008 Fair Oaks Labs, Inc.\nCopyright (c) 2017 Mauro\
    \ Bringolf\nCopyright (c) 2018 Sven Sauleau <sven@sauleau.com>\nCopyright (c)\
    \ Facebook, Inc. and its affiliates\nCopyright 2012 The Obvious Corporation\n\
    Copyright 2012 The Obvious Corporation. http://obvious.com/"
  downloadLocation: "NONE"
  externalRefs:
  - referenceCategory: "PACKAGE_MANAGER"
    referenceType: "purl"
    referenceLocator: "pkg:npm/%40webassemblyjs/wast-parser@1.9.0"
  filesAnalyzed: false
  homepage: "https://github.com/xtuc/webassemblyjs#readme"
  licenseConcluded: "NOASSERTION"
  licenseDeclared: "MIT"
  name: "wast-parser"
  summary: "WebAssembly text format parser"
  versionInfo: "1.9.0"
- SPDXID: "SPDXRef-Package-NPM-webassemblyjs-wast-parser-1.9.0-vcs"
  copyrightText: "Copyright (c) 2008 Fair Oaks Labs, Inc.\nCopyright (c) 2017 Mauro\
    \ Bringolf\nCopyright (c) 2018 Sven Sauleau <sven@sauleau.com>\nCopyright (c)\
    \ Facebook, Inc. and its affiliates\nCopyright 2012 The Obvious Corporation\n\
    Copyright 2012 The Obvious Corporation. http://obvious.com/"
  downloadLocation: "git+https://github.com/xtuc/webassemblyjs.git@0440b420888c1f7701eb9762ec657775506b87d8"
  externalRefs:
  - referenceCategory: "PACKAGE_MANAGER"
    referenceType: "purl"
    referenceLocator: "pkg:npm/%40webassemblyjs/wast-parser@1.9.0"
  filesAnalyzed: false
  homepage: "https://github.com/xtuc/webassemblyjs#readme"
  licenseConcluded: "NOASSERTION"
  licenseDeclared: "NOASSERTION"
  name: "wast-parser"
  summary: "WebAssembly text format parser"
  versionInfo: "1.9.0"
```

Same version of webassemblyjs is duplicated (one with licenseDeclared determined, the other with NOASSERTION), I assume that it is because it was depended from two packages.

Is this expected? Shouldn't be only one entry? (with the same licensing data?). I see that one SPDXID shows that it comes from vcs and the other does not, but this causes us to post process this SPDX file and de-duplicate these entries.
