### DISCUSSION TITLE
Usage of `SpdxDocumentFile` package manager and `ort.yml`

### DISCUSSION THREAD

**Discussion by maennchen** [oss-review-toolkit/ort#9904] [Q&A] [answered]
I'm currently implementing Source SBoMs for the Elixir programming language. To get as much detail into it as possible and also get adequate CycloneDX output (only contains packages, not project), I would like to change my `project.spdx.yml` to include the software components.

Before:

```yml
SPDXID: "SPDXRef-DOCUMENT"
spdxVersion: "SPDX-2.2"
creationInfo:
  created: "2025-02-05T12:29:35Z"
  creators:
  - "Organization: The Elixir Team"
  licenseListVersion: "3.9"
name: "elixir"
dataLicense: "CC0-1.0"
documentNamespace: "https://github.com/elixir-lang/elixir"
documentDescribes:
- "SPDXRef-Package-elixir"
packages:
- SPDXID: "SPDXRef-Package-elixir"
  summary: "About Elixir is a dynamic, functional language for building scalable and maintainable applications"
  copyrightText: "Copyright (c) 2012 Plataformatec. Copyright (c) 2021 The Elixir Team. All Rights Reserved."
  downloadLocation: "git+https://github.com/elixir-lang/elixir.git"
  filesAnalyzed: false
  homepage: "https://elixir-lang.org/"
  licenseConcluded: "Apache-2.0 AND LicenseRef-scancode-unicode"
  licenseDeclared: "Apache-2.0 AND LicenseRef-scancode-unicode"
  name: "elixir"
  packageFileName: "./"
  externalRefs:
    - referenceCategory: PACKAGE-MANAGER
      referenceType: "purl"
      referenceLocator: "pkg:otp/elixir"
      comment: "OTP PURL"
```

After:

```yml
SPDXID: "SPDXRef-DOCUMENT"
spdxVersion: "SPDX-2.2"
creationInfo:
  created: "2025-02-05T12:29:35Z"
  creators:
  - "Organization: The Elixir Team"
  licenseListVersion: "3.9"
name: "elixir"
dataLicense: "CC0-1.0"
documentNamespace: "https://github.com/elixir-lang/elixir"
documentDescribes:
- "SPDXRef-Package-elixir-lang"
packages:
- SPDXID: "SPDXRef-Package-elixir-lang"
  summary: "About Elixir is a dynamic, functional language for building scalable and maintainable applications"
  copyrightText: "Copyright (c) 2012 Plataformatec. Copyright (c) 2021 The Elixir Team. All Rights Reserved."
  downloadLocation: "git+https://github.com/elixir-lang/elixir.git"
  filesAnalyzed: false
  homepage: "https://elixir-lang.org/"
  licenseConcluded: "Apache-2.0 AND LicenseRef-scancode-unicode"
  licenseDeclared: "Apache-2.0 AND LicenseRef-scancode-unicode"
  name: "elixir-lang"
  externalRefs:
    - referenceCategory: PACKAGE-MANAGER
      referenceType: "purl"
      referenceLocator: "pkg:github/elixir-lang/elixir"
      comment: "GitHub PURL"
- SPDXID: "SPDXRef-Package-eex"
  summary: "About Elixir is a dynamic, functional language for building scalable and maintainable applications"
  copyrightText: "Copyright (c) 2012 Plataformatec. Copyright (c) 2021 The Elixir Team. All Rights Reserved."
  downloadLocation: "git+https://github.com/elixir-lang/elixir.git"
  filesAnalyzed: false
  homepage: "https://elixir-lang.org/"
  licenseConcluded: "Apache-2.0"
  licenseDeclared: "Apache-2.0"
  name: "eex"
  packageFileName: "./lib/eex"
  externalRefs:
    - referenceCategory: PACKAGE-MANAGER
      referenceType: "purl"
      referenceLocator: "pkg:otp/eex"
      comment: "OTP PURL"
- SPDXID: "SPDXRef-Package-elixir"
  summary: "About Elixir is a dynamic, functional language for building scalable and maintainable applications"
  copyrightText: "Copyright (c) 2012 Plataformatec. Copyright (c) 2021 The Elixir Team. All Rights Reserved."
  downloadLocation: "git+https://github.com/elixir-lang/elixir.git"
  filesAnalyzed: false
  homepage: "https://elixir-lang.org/"
  licenseConcluded: "Apache-2.0 AND LicenseRef-scancode-unicode"
  licenseDeclared: "Apache-2.0 AND LicenseRef-scancode-unicode"
  name: "elixir"
  packageFileName: "./lib/elixir"
  externalRefs:
    - referenceCategory: PACKAGE-MANAGER
      referenceType: "purl"
      referenceLocator: "pkg:otp/elixir"
      comment: "OTP PURL"
- SPDXID: "SPDXRef-Package-exunit"
  summary: "About Elixir is a dynamic, functional language for building scalable and maintainable applications"
  copyrightText: "Copyright (c) 2012 Plataformatec. Copyright (c) 2021 The Elixir Team. All Rights Reserved."
  downloadLocation: "git+https://github.com/elixir-lang/elixir.git"
  filesAnalyzed: false
  homepage: "https://elixir-lang.org/"
  licenseConcluded: "Apache-2.0"
  licenseDeclared: "Apache-2.0"
  name: "exunit"
  packageFileName: "./lib/ex_unit"
  externalRefs:
    - referenceCategory: PACKAGE-MANAGER
      referenceType: "purl"
      referenceLocator: "pkg:otp/ex_unit"
      comment: "OTP PURL"
- SPDXID: "SPDXRef-Package-iex"
  summary: "About Elixir is a dynamic, functional language for building scalable and maintainable applications"
  copyrightText: "Copyright (c) 2012 Plataformatec. Copyright (c) 2021 The Elixir Team. All Rights Reserved."
  downloadLocation: "git+https://github.com/elixir-lang/elixir.git"
  filesAnalyzed: false
  homepage: "https://elixir-lang.org/"
  licenseConcluded: "Apache-2.0"
  licenseDeclared: "Apache-2.0"
  name: "iex"
  packageFileName: "./lib/iex"
  externalRefs:
    - referenceCategory: PACKAGE-MANAGER
      referenceType: "purl"
      referenceLocator: "pkg:otp/iex"
      comment: "OTP PURL"
- SPDXID: "SPDXRef-Package-logger"
  summary: "About Elixir is a dynamic, functional language for building scalable and maintainable applications"
  copyrightText: "Copyright (c) 2012 Plataformatec. Copyright (c) 2021 The Elixir Team. All Rights Reserved."
  downloadLocation: "git+https://github.com/elixir-lang/elixir.git"
  filesAnalyzed: false
  homepage: "https://elixir-lang.org/"
  licenseConcluded: "Apache-2.0"
  licenseDeclared: "Apache-2.0"
  name: "logger"
  packageFileName: "./lib/logger"
  externalRefs:
    - referenceCategory: PACKAGE-MANAGER
      referenceType: "purl"
      referenceLocator: "pkg:otp/logger"
      comment: "OTP PURL"
- SPDXID: "SPDXRef-Package-mix"
  summary: "About Elixir is a dynamic, functional language for building scalable and maintainable applications"
  copyrightText: "Copyright (c) 2012 Plataformatec. Copyright (c) 2021 The Elixir Team. All Rights Reserved."
  downloadLocation: "git+https://github.com/elixir-lang/elixir.git"
  filesAnalyzed: false
  homepage: "https://elixir-lang.org/"
  licenseConcluded: "Apache-2.0"
  licenseDeclared: "Apache-2.0"
  name: "mix"
  packageFileName: "./lib/mix"
  externalRefs:
    - referenceCategory: PACKAGE-MANAGER
      referenceType: "purl"
      referenceLocator: "pkg:otp/mix"
      comment: "OTP PURL"
- SPDXID: "SPDXRef-Package-erlang"
  description: "Erlang is a programming language and runtime system for building massively scalable soft real-time systems with requirements on high availability."
  copyrightText: "Copyright Ericsson AB 2010-2024. All Rights Reserved."
  downloadLocation: "git+https://github.com/erlang/otp.git"
  filesAnalyzed: false
  homepage: "https://www.erlang.org/"
  licenseConcluded: "NOASSERTION"
  licenseDeclared: "Apache-2.0"
  name: "erlang"
  externalRefs:
    - referenceCategory: PACKAGE-MANAGER
      referenceType: "purl"
      referenceLocator: "pkg:github/erlang/otp"
      comment: "GitHub PURL"
relationships:
- spdxElementId: "SPDXRef-Package-elixir-lang"
  relatedSpdxElement: "SPDXRef-Package-eex"
  relationshipType: "STATIC_LINK" # Should be CONTAINS, issue with ORT
- spdxElementId: "SPDXRef-Package-elixir-lang"
  relatedSpdxElement: "SPDXRef-Package-elixir"
  relationshipType: "STATIC_LINK" # Should be CONTAINS, issue with ORT
- spdxElementId: "SPDXRef-Package-elixir-lang"
  relatedSpdxElement: "SPDXRef-Package-exunit"
  relationshipType: "STATIC_LINK" # Should be CONTAINS, issue with ORT
- spdxElementId: "SPDXRef-Package-elixir-lang"
  relatedSpdxElement: "SPDXRef-Package-iex"
  relationshipType: "STATIC_LINK" # Should be CONTAINS, issue with ORT
- spdxElementId: "SPDXRef-Package-elixir-lang"
  relatedSpdxElement: "SPDXRef-Package-logger"
  relationshipType: "STATIC_LINK" # Should be CONTAINS, issue with ORT
- spdxElementId: "SPDXRef-Package-elixir-lang"
  relatedSpdxElement: "SPDXRef-Package-mix"
  relationshipType: "STATIC_LINK" # Should be CONTAINS, issue with ORT
- spdxElementId: "SPDXRef-Package-elixir"
  relatedSpdxElement: "SPDXRef-Package-erlang"
  relationshipType: "RUNTIME_DEPENDENCY_OF"
- spdxElementId: "SPDXRef-Package-eex"
  relatedSpdxElement: "SPDXRef-Package-elixir"
  relationshipType: "STATIC_LINK"
- spdxElementId: "SPDXRef-Package-exunit"
  relatedSpdxElement: "SPDXRef-Package-elixir"
  relationshipType: "STATIC_LINK"
- spdxElementId: "SPDXRef-Package-iex"
  relatedSpdxElement: "SPDXRef-Package-elixir"
  relationshipType: "STATIC_LINK"
- spdxElementId: "SPDXRef-Package-logger"
  relatedSpdxElement: "SPDXRef-Package-elixir"
  relationshipType: "STATIC_LINK"
- spdxElementId: "SPDXRef-Package-mix"
  relatedSpdxElement: "SPDXRef-Package-elixir"
  relationshipType: "STATIC_LINK"
```

Unfortunately by doing that, the exclusions and curations (license findings) are no longer applied.

I tried to work around the issue with the following approaches:
* Copy relevant parts of `.ort.yml` into the respective components (absolute / relative paths)
* Create package configurations in ort config directory
* Create package configurations in `.ort.yml` and enable `enableRepositoryPackageConfigurations`.

Did I implement things correctly and is what I'm trying to do even possible with ORT as it is right now?

Context:
* Change Commit: https://github.com/maennchen/elixir/commit/671d75764acd4d5dfd83ed52f1752ecf14c7b87e
* CI Execution Before: https://github.com/maennchen/elixir/actions/runs/13210025633
  ![image](https://github.com/user-attachments/assets/f7b1a319-7ba5-497d-b69b-c58198160f90)
* CI Execution After: https://github.com/maennchen/elixir/actions/runs/13210254304
  ![image](https://github.com/user-attachments/assets/9e8da0e2-5dab-453f-ab39-ac757a07e8c7)
