### ISSUE TITLE
orth package-configuration create does not respect VCS path curations

### ISSUE THREAD

**Issue by tsteenbe** [oss-review-toolkit/ort#10178]
### Describe the bug

Generating package configurations with ORT helper cli (orth) using `orth package-configuration create` or via [orthw shell](https://github.com/oss-review-toolkit/orthw-shell) does not filter out path excludes paths based on VCS path curations.

### To Reproduce

Use these test project [ort-pc-generation-incorrect-path-excludes-issue.zip](https://github.com/user-attachments/files/19774001/ort-pc-generation-incorrect-path-excludes-issue.zip) or follow instructions below.

1. Create a package-list.yml with below contents

```
---
projectName: "Example project name"
projectVcs:
  type: "Git"
  url: "https://github.com/example/project.git"
  revision: "2222222222222222222222222222222222222222"
  path: "vcs-path/project"
dependencies:
  - id: "Maven:org.niis.xrd4j:server:0.6.0"
    vcs:
      type: "Git"
      url: "https://github.com:nordic-institute/xrd4j.git"
      revision: "3a2d50b539558b1f41058169c7ce3b24e953c0a1"
    sourceArtifact:
      url: "https://artifactory.niis.org/artifactory/xroad-maven-releases/org/niis/xrd4j/server/0.6.0/server-0.6.0-sources.jar"
    isExcluded: true
    isDynamicallyLinked: true

```
2. Generate a ORT analyzer result file via `orth create-analyzer-result-from-package-list -i package-list.yml -o ./analyzer-result.yml`
3. Generate a ORT scanner result file via `ort scan -i analyzer-result.yml -o ./ `
4. Initiate scan result with [orthw shell](https://github.com/oss-review-toolkit/orthw-shell) e.g. `orthw init file://${PWD}/scan-result.yml`
5. Generate a package configuration file for package `Maven:org.niis.xrd4j:server:0.6.0` via `orthw pc-create Maven:org.niis.xrd4j:server:0.6.0`

This will result in the creation of `<YOUR_ORT_CONFIG_LOCATION>/package-configurations/Maven/org.niis.xrd4j/server/0.6.0/vcs.yml` with the following contents:

```
---
id: "Maven:org.niis.xrd4j:server:0.6.0"
vcs:
  type: "Git"
  url: "https://github.com/nordic-institute/xrd4j.git"
  revision: "3a2d50b539558b1f41058169c7ce3b24e953c0a1"
path_excludes:
- pattern: "example-adapter/**"
  reason: "DOCUMENTATION_OF"
- pattern: "src/buildSrc/**"
  reason: "BUILD_TOOL_OF"
- pattern: "src/client/src/test/**"
  reason: "TEST_OF"
- pattern: "src/common/src/test/**"
  reason: "TEST_OF"
- pattern: "src/gradlew.bat"
  reason: "BUILD_TOOL_OF"
- pattern: "src/rest/src/test/**"
  reason: "TEST_OF"
- pattern: "src/server/src/integrationTest/**"
  reason: "TEST_OF"
- pattern: "src/server/src/test/**"
  reason: "TEST_OF"
```

### Expected behavior

There a existing [package configuration](https://github.com/oss-review-toolkit/ort-config/blob/ae9858423b7bd17212e9c2391fd0cb71388712fc/curations/Maven/org.niis.xrd4j/server.yml#L4) in the ort-config repository for `Maven:org.niis.xrd4j:server` with following contents:

```
- id: "Maven:org.niis.xrd4j:server"
  curations:
    comment: |
      Non-standard path within the repository.
    vcs:
      path: "src/server"
```

Expected package configuration generation to respect above VCS path curation so it should something like the below:
```
---
id: "Maven:org.niis.xrd4j:server:0.6.0"
vcs:
  type: "Git"
  url: "https://github.com/nordic-institute/xrd4j.git"
  revision: "3a2d50b539558b1f41058169c7ce3b24e953c0a1"
path_excludes:
- pattern: "src/server/src/integrationTest/**"
  reason: "TEST_OF"
- pattern: "src/server/src/test/**"
  reason: "TEST_OF"
```
### Environment

* ORT version: 56.1.0-007.sha.865b49b
* ORT config repository version: ae98584
* Java version:  JDK 21.0.6+7-LTS
* OS: MacOS 15.3.2 (24D81)
