### ISSUE TITLE
Add resolutions for false-positive scanner matches

### ISSUE THREAD

**Issue by tsteenbe** [oss-review-toolkit/ort#1130]
Whatever license scanner you use there also will be false-positives which I would subdivide in:

- Correct match but the license found is not applicable
- Incorrect match e.g. cases where “version 2.0” results in a LGPL-2.1 match

We should offer ORT user a way to resolve these scanner false-positives.
Proposal add mechanism to ORT that understand below to .ort.yml or global configuration specification and then ignore the license in the Evaluator and displays comment why this is a false-positive license match in the reports

```
  - id: “Maven:com.google.protobuf:protobuf-java:*"
    matches:
       path: "conformance/third_party/jsoncpp/json.h"
       license: (GPL-1.0 OR GPL-2.0 OR GPL-3.0)
       reason: "FALSE_POSITIVE"
       comment: "Matches on ‘The MIT license is compatible with both the GPL and commercial software’"
```

https://github.com/google/qrisp/blob/master/google/protobuf/conformance/third_party/jsoncpp/json.h
https://github.com/google/qrisp/blob/master/google/protobuf/conformance/third_party/jsoncpp/jsoncpp.cpp
