### ISSUE TITLE
Make it possible to export license texts as txt.

### ISSUE THREAD

**Issue by flixx** [oss-review-toolkit/ort#1788]
As a enterprise software distributor, we must be able to bundle all our open-source license textes and distribute them along with our software.

Is there a way to not only scan the licence texts but also to export them into a folder?

If not this may be a feature request :)

Felix

**Comment by sschuberth** [comment]
Hi @flixx, thanks for giving ORT a try! The existing way to bundle open-source license texts is to use the reporter with the `NOTICE` file output format. Examples for such NOTICE files can be found as part of the [test assets](https://github.com/heremaps/oss-review-toolkit/tree/master/reporter/src/funTest/assets), e.g. [here](https://github.com/heremaps/oss-review-toolkit/blob/master/reporter/src/funTest/assets/npm-test-without-exclude-expected-NOTICE).

Note, however, that currently the license texts are "normalized" in the sense that not *exactly* the license texts as found in the source code are used, but the *original* license texts as defined by the respective license. That is, for example if someone customized an original Apache-2.0 license text in some trivial way, like formatting changes etc., not that changed text is used, but the original / "upstream" version of the Apache-2.0 license text.

**Comment by flixx** [comment]
@sschuberth Nice, I was not aware of that feature.

This almost is usable for us.

1.  What is the reasoning behind having the License texts normalised? I would guess that legally, distributors are obligated to provide the original license text.

2. As we deal with over 1000 licenses, it would be great to have some Meta-Data at the top of each license text. Something like

```
----
[package name] [package version] - [licence type] [...whatever useful information there is available...]

[license text]
----

What do you think?
Felix

**Comment by sschuberth** [comment]
> What is the reasoning behind having the License texts normalised?

Simplicity of the implementation and technical restrictions of the license scanner. Also scan results would become huge if for every license finding the full text would be stored.

> I would guess that legally, distributors are obligated to provide the original license text.

Opinions on that vary depending on who you ask, even across lawyers 😉 Of course you're on the safe side if you always provide the original license text. But what if the text is just prefixed with some programming language specific comment character? That's still the same text, or? What about formatting / indentation changes, like tabs vs. spaces? I'd personally say that's again still the same text. The list could go on with word-wrapping changes, trivial wording changes, etc. and it's hard to draw the line here (programmatically). In the end, what counts is the intent (not necessarily the exact choice of words expressing the intent) of the license. So it's probably acceptable in many (but maybe not all) cases to use the same original / upstream license text for all findings of a particular license.

Anyway, I agree there's room for improvement, but the problem is not that easy to solve if you do not want to use a sledge hammer and blindly copy all full found license texts.

**Comment by tsteenbe** [comment]
@flixx We will be refactoring the notice generator soon to output the main license per package + version. The main license being the exact copy of the LICENSE, COPYING, NOTICE, etc. as found in the repository/sources archive of the OSS package.  Still ongoing discussion how to handle license statements found in code files as per @sschuberth points above - complex issue.

Some ideas on how notices could look like
```
----
PackageName: <package id>
PackageVersion: <package version>
PackageLicenseDeclared: <declared license processed as SPDX> (declared license)
PackageHomePage: [url]

<Print license text of main license file it not exact match of normalized OSS license text>
<BSD license are often customized but Apache, MIT and GPL are usually the same>
----

<Print normalized OSS license texts like Apache-2.0 or MIT>
```

**Comment by flixx** [comment]
Wow, thanks for your responses and ideas so far.
Thanks!

> Do you really mean 1000 (unique) licenses, or 1000 dependencies?
1000 dependencies of curse ;).

I must say, I don't really understand the benefit yet, of copying the normalised licences into the report. Let me list here a couple of packages with special licenses:

* [PIL](https://github.com/python-pillow/Pillow/blob/master/LICENSE) seems to use a modified version of MIT
* [Supervisor](https://raw.githubusercontent.com/Supervisor/supervisor/master/LICENSES.txt) seems to use a modified version of BSD
* [Nginx](https://en.wikipedia.org/wiki/Nginx) only has a " BSD-like license." They seem to have removed the last paragraph of BSD-2.
* Also checkout [this Website](https://fedoraproject.org/wiki/Licensing:MIT). It shows over 20 (!) different versions of the MIT License

So, having the normalised licence texts copied would IMHO just lead to confusion.

I understand that copying LICENSE, COPYING, NOTICE files is relatively simple compared to license statements found in code files. I would also guess that ~90% of open source packages would have those files.

For me it seems the easiest way to solve that is to copy over those files that are found and leave the space empty if LICENSE, COPYING, NOTICE files are not found, or mark it as `<LICENSE File not found>`. We could post-process this file then manually.

Thanks again,
Felix

**Comment by tsteenbe** [comment]
@flixx Familiar with the [PIL](https://github.com/python-pillow/Pillow/blob/master/LICENSE) case which is not in ScanCode. The way we handle these cases is to [conclude the license using a curation](https://github.com/heremaps/oss-review-toolkit/blob/master/docs/Configuration.md#curating-metadata-of-packages) for a package, for example LicenseRef-ORT-PIL.  Then when execute the Reporter to generate notices with param `--custom-license-texts-dir` and point it to a directory that has a file LicenseRef-ORT-PIL containing the PIL license text.

We do not want ORT to have its own license collection, we always upstream to ScanCode and SPDX any licenses we need an identifier for. The `--custom-license-texts-dir` just enable use to continue doing OSS reviews and not having to wait until our Pull Requests are merged and it also useful for handling proprietary/commercial licenses.

Regarding notices - the real way forward is for ORT to support generation of notices in [SPDX](http://spdx.org) which is an open standard that can both handle LICENSE, COPYING, NOTICE files is relatively simple compared to license statements found in code files. Implementation of SPDX support is a work in progress, lots of prep work needed like https://github.com/heremaps/oss-review-toolkit/pull/1790.

**Comment by peterhsshin** [comment]
@tsteenbe It was good to meet you at the OS Summit.  Our company is working on integrating our tool to address this issue.  License Analyzer(LiAN) extracts copyright texts and license statements as shown in the source code.  We installed ORT locally and started looking into code structure and input/output to see how we can integrate our results into the existing workflow.

**Comment by tsteenbe** [comment]
@peterhsshin Sorry missed the notification on this issue. It was good to meet you as well. The biggest issue is that scanner like ScanCode can give us a match but not the entire license text within a code comment.  Does License Analyzer(LiAN) solve this issue?

**Comment by tsteenbe** [comment]
@flixx  Minor status update @mnonnenmacher has been making good progress, if all goes well by the end of this month ORT should be able to produce notices that include the copies of LICENSE, COPYING, etc. e.g. main license files.

**Comment by sschuberth** [comment]
@tsteenbe, as [commented](https://github.com/nexB/scancode-toolkit/issues/504#issuecomment-542721767) by @pombredanne the issue with ScanCode should be solved now.

**Comment by peterhsshin** [comment]
@tsteenbe Yes, LiAn identifies the altered license text as shown in the comment section.  Furthermore, it also identifies variously formatted copyright statements that can span over multiple lines.

**Comment by tsteenbe** [comment]
@flixx  Forgot to update this ticket but you if you call the `reporter` with the `-f NoticeByPackage` you will get the notices with the copyright holders and licenses specified per package. To customize the notices please see https://github.com/heremaps/oss-review-toolkit/blob/master/docs/notice-pre-processor-kts.md

**Comment by pombredanne** [comment]
@tsteenbe you wrote: https://github.com/heremaps/oss-review-toolkit/issues/1788#issuecomment-543911539

> The biggest issue is that scanner like ScanCode can give us a match but not the entire license text within a code comment. 

Actually the latest incarnation (in Git head) of the --license-text option return the full license text match now and has been for a while. You should give it a try!

**Comment by sschuberth** [comment]
We know @pombredanne, see [my comment above](https://github.com/heremaps/oss-review-toolkit/issues/1788#issuecomment-543914758) 😉

**Comment by flixx** [comment]
Hi @sschuberth @tsteenbe 
I finally found some time to test it on parts of our repo and have to say that I'm quite impressed!

I successfully generated a `NOTICE_BY_PACKAGE` file from our `requirements.txt` with 163 entries. Great!

Looking at the file, I see that it contains 

* 168 packages (searched for `package: `)
* 106 main-license files (searched for `This package contains the file`)
* ~ 988 source-code licenses (searched for `----`)

Taking a few samples from packages that don't seems to have a main-license, I found, that at least some of them do have a LICENCE file that is for some reason not found. Some examples are:

- urllib3:1.25.6 https://github.com/urllib3/urllib3/blob/1.25.6/LICENSE.txt
- structlog:19.1.0 https://github.com/hynek/structlog/blob/master/LICENSE
- pillow:6.2.0 https://github.com/python-pillow/Pillow/blob/master/LICENSE

Do you know why that is?

Also, do I understand it correctly, that the the findings from ScanCode to find the source-code licences for which then the SPDX templates are inserted? ScanCode seems to find some licenses in the packages, which seems wrong for me (e.g. 3 times GPL for https://github.com/django/django ). But I guess that would be an issue for ScanCode then ;)

Thanks for everyone who worked at this.
Felix

**Comment by sschuberth** [comment]
@mnonnenmacher probably is in the best position to answer our questions as he's the one who implemented the `NOTICE_BY_PACKAGE` reporter.

**Comment by mnonnenmacher** [comment]
@flixx Please check the following things to narrow down the issue:

In the `scan-result.yml` check what the provenance is for the three packages. This will show what was scanned, just to verify that the correct sources were scanned. The entries will look like this:

```
    - id: "NPM::mime-db:1.33.0"
      results:
      - provenance:
          download_time: "2019-10-28T13:27:42.489324Z"
          vcs_info:
            type: "Git"
            url: "https://github.com/jshttp/mime-db.git"
            revision: "e7c849b1c70ff745a4ae456a0cd5e6be8b05c2fb"
            resolved_revision: "e7c849b1c70ff745a4ae456a0cd5e6be8b05c2fb"
            path: ""
          original_vcs_info:
            type: "Git"
            url: "https://github.com/jshttp/mime-db.git"
            revision: "e7c849b1c70ff745a4ae456a0cd5e6be8b05c2fb"
            path: ""
        scanner:
          ...
```

Check if the license files were archived at all. By default they are stored in `~/.ort/scanner/archive/`. This will show if the issue was in the scanner while archiving the license files, or in the reporter while including them in the report.

**Comment by flixx** [comment]
Hi @mnonnenmacher 

here is the snipped of `scan-result.yml`

```
   - id: "PyPI::urllib3:1.25.6"
      results:
      - provenance:
          download_time: "2020-01-22T14:28:44.445027Z"
          source_artifact:
            url: "https://files.pythonhosted.org/packages/ff/44/29655168da441dff66de03952880c6e2d17b252836ff1aa4421fba556424/urllib3-1.25.6.tar.gz"
            hash:
              value: "a7504a9fcb7ed4ffa482fe098c80b6d4"
              algorithm: "MD5"
        scanner:
          name: "ScanCode"
          version: "3.0.2"
          configuration: "--copyright --license --ignore *.ort.yml --info --strip-root\
            \ --timeout 300 --ignore HERE_NOTICE --ignore META-INF/DEPENDENCIES --json-pp"
        summary:
          start_time: "2020-01-22T14:28:44.800160Z"
          end_time: "2020-01-22T14:29:00.235434Z"
          file_count: 134
          package_verification_code: "8450c4d67d2d5d569839fe68475f79bea997e468"
```

In the `urllib3-1.25.6.tar.gz`, there is a `LICENSE.txt` present.

The `archive.zip` for urllib seems to be corrupt (22 byte). 

```
$ zip -T archive.zip                                                                                                    
$ zip error: Nothing to do! (archive.zip)
```

Does this help somehow?
