### ISSUE TITLE
Test scope exclusion ignored when scanning Maven project

### ISSUE THREAD

**Issue by oova** [oss-review-toolkit/ort#2206]
I have a simple Maven project which contains only the following two files (located in the project's root directory):

`pom.xml`
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.example.ort</groupId>
    <artifactId>ort-demo</artifactId>
    <version>1.0</version>

    <dependencies>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>28.2-jre</version>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>5.6.0</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
```

`.ort.yml`
```yaml
excludes:
  scopes:
  - pattern: "provided"
    reason: "PROVIDED_DEPENDENCY_OF"
    comment: "Scope with dependencies provided by the JDK or container at runtime. Not included in released artifacts in the context of this project."
  - pattern: "test"
    reason: "TEST_DEPENDENCY_OF"
    comment: "Scope with dependencies only used for development. Not included in released artifacts in the context of this project."
```

When I run the scanner and the reporter on this project and look at the results, the dependencies with test scope will be scanned and shown in the report although I expected them to be excluded based on the `.ort.yml` file.

I get the same results when I run the scanner with the `--scopes compile` option.

Is this a bug or did I make a mistake?

Thanks
Uwe
