### ISSUE TITLE
Notice curations

### ISSUE THREAD

**Issue by tsteenbe** [oss-review-toolkit/ort#2265]
Add an option to ORT to allow manually specifying the notices to use for a specific package.

Use cases: 
A) Main license file for OSS package contains the wrong license e.g. package was relicensed but main license file was not updated.
B) The project has a main license but only mentioned in the code and there is no main license file such as LICENSE or COPYING.
C) Main license file for OSS package contains multiple licenses or other references not applicable to the currently packages. Example a package comes from a repository that hold multiple packages such as https://github.com/apache/flink

*Proposal*

Allow setting of `notice_file` in [curations.yml](https://github.com/heremaps/oss-review-toolkit/blob/master/docs/config-file-curations-yml.md) which point to a local file.

```
- id: "NPM::ast-traverse:0.1.0"
  curations:
    comment: "Setting notice file as LICENSE in the repository contains other text that irrelevant for open source notices."
    notice_file: [ort-configuration-path]/notices/ast-traverse-0.1.0.txt
```

From Slack discussion with @apfelkraut
