### ISSUE TITLE
scan mime-types error

### ISSUE THREAD

**Issue by freedom-wy** [oss-review-toolkit/ort#2418]
```
The following package managers are activated:
	Bower, Bundler, Cargo, Conan, DotNet, GoDep, GoMod, Gradle, Maven, NPM, NuGet, PhpComposer, PIP, Pipenv, Pub, SBT, Stack, Yarn
Analyzing project path:
	/home/user1/mime-types
14:08:41.040 [analyzer-1] ERROR java.lang.Object - Resolving dependencies for 'package.json' failed with: IllegalArgumentException: No lockfile found in '.'. This potentially results in unstable versions of dependencies. To allow this, enable support for dynamic versions.
Found 1 project(s) in total.
Writing analyzer result to '/home/user1/test/analyzer-result.yml'.
```

What should I do？

```
java -version
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-8u242-b08-0ubuntu3~18.04-b08)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)
 node -v
v13.11.0
nodejs -v
v12.16.1
npm -v
6.13.4
```

```
  result:
    projects:
    - id: "NPM::package.json:"
      definition_file_path: "package.json"
      declared_licenses: []
      declared_licenses_processed: {}
      vcs:
        type: ""
        url: ""
        revision: ""
        path: ""
      vcs_processed:
        type: "Git"
        url: "https://github.com/jshttp/mime-types.git"
        revision: "076f7902e3a730970ea96cd0b9c09bb6110f1127"
        path: ""
      homepage_url: ""
      scopes: []
    packages: []
    issues:
      'NPM::package.json:':
      - timestamp: "2020-03-26T06:08:41.045Z"
        source: "NPM"
        message: "Resolving dependencies for 'package.json' failed with: IllegalArgumentException:\
          \ No lockfile found in '.'. This potentially results in unstable versions\
          \ of dependencies. To allow this, enable support for dynamic versions."
        severity: "ERROR"
    has_issues: true
scanner: null
evaluator: null
```
