### ISSUE TITLE
excludes and scancode

### ISSUE THREAD

**Issue by fb33** [oss-review-toolkit/ort#2972]
Hello,

I've a question about the configuration of exclude paths for the scanner.
I've got a repository configuration file where I put some lines like :
```
excludes:
  paths:
    - pattern: "**/*.spec.ts"
      reason: "TEST_OF"
      comment: "tests files."
    - pattern: "test/**"
      reason: "TEST_OF"
      comment: "tests files."
    - pattern: "docs/**"
      reason: "DOCUMENTATION_OF"
      comment : "documentation files"

```
I run the analyzer with that config and then I run the scanner with the "--skip-excluded" option but I still have some violations for files in paths that are excluded.
Example : "GPL-1.0-or-later" found in "test/qunit/qunit.js" for NPM::winchan:0.2.2 package

What do i miss ?
Thanks for your help.

**Comment by fviernau** [comment]
The the `repository configuration` applies only to the source code repository you `analyzed`, but not to (all) dependencies / packages. Excluding files in dependencies can be done only via a `package configuration` [1].
However, the `--skip-excluded` option does not handle file granularity excludes: It considers only whether the whole package is excluded. So you'd probably want to know how you can exclude the package `NPM::winchan:0.2.2`. You can do this only by either excluding all `scopes` which reference this package, or by excluding all projects which reference this package.

So when you managed to exclude the package as described, please check whether your `evaluator rules` for the `GPL-1.0-or-later` do adhere to the excluded state of packages. Note that rules may also ignore the excluded state.

Does this help, @fb33 ?




[1] https://github.com/oss-review-toolkit/ort/blob/master/docs/config-file-package-configuration-yml.md

**Comment by fb33** [comment]
My problem is that GPL-1.0-or-later is actually a detected license in a file only use for test (as its path suggest).
I'll have a look to the package configuration. It seems to be the right configuration.
Thanks

**Comment by fb33** [comment]
I wrote this conf : 
```
- id: "NPM::winchan:0.2.2"
  source_artifact_url: https://registry.npmjs.org/winchan/-/winchan-0.2.2.tgz
  path_excludes:
  - pattern: "test/**"
    reason: "TEST_OF"
    comment: "This directory contains test files which are not under our OSS policy.."
```
finally, the package configuration doesn't fix my problem. The GPL rule is still violated for this package.

I'll use the rules resolution as workaround to go on my global projects configuration
