### ISSUE TITLE
[scan-result.yml] has_errors to has_issues column_name change 

### ISSUE THREAD

**Issue by BennyThink** [oss-review-toolkit/ort#3251]
hi,

In `scan-result.yml`, I remember there was `has_errors`, and now there is `has_issues`.

From [this line](https://github.com/oss-review-toolkit/ort/blob/3543d1c48c83108f86a2302785c68ac328cfd486/model/src/main/kotlin/ScanRecord.kt#L31), I can see such comments
```kotlin
 value = ["has_issues", /* Backwards-compatibility: */ "has_errors", "scanned_scopes", "scopes"],
```

But actually there was no `has_errors` though the above comment `Backwards-compatibility` . Is it an intended behavior? It looks weird compare to the code I found and[ this PR](https://github.com/oss-review-toolkit/ort/pull/2140).

By the way, is there any particular reason that the column name has changed from `has_errors` to `has_errors`?

Thanks!

Attach files are my scan result
[scan-result.yml.zip](https://github.com/oss-review-toolkit/ort/files/5443135/scan-result.yml.zip)

**Comment by sschuberth** [comment]
I'm a bit confused now, because at first you're saying "I remember there was `has_errors`", but then you say "But actually there was no `has_errors`".

Fact is, https://github.com/oss-review-toolkit/ort/commit/addb4abb3a25c2b52cab9471e9fcb32dc0569445 renamed `has_errors` to `has_issues` (and the rationale is given in the commit message), but we at first forgot to add backwards-compatibility so that result files that still use `has_errors` could still be *de*serialized. That backwards-compatibility was added in the [PR](https://github.com/oss-review-toolkit/ort/pull/2140) you're linking to.

**Comment by BennyThink** [comment]
Thanks!
```yml
---
repository:
  vcs:
    type: ""
    url: ""
    revision: ""
    path: ""
  vcs_processed:
    type: ""
    url: ""
    revision: ""
    path: ""
  config: {}
analyzer: null
scanner:
  start_time: "2020-10-27T05:10:28.774747Z"
  end_time: "2020-10-27T05:11:47.810211Z"
  environment:
    ort_version: "0.1.0-SNAPSHOT"
    java_version: "11.0.8"
    os: "Linux"
    processors: 4
    max_memory: 2088763392
    variables:
      TERM: "xterm"
      JAVA_HOME: "/opt/java/openjdk"
      ANDROID_HOME: "/opt/android-sdk"
      GOPATH: "/go"
    tool_versions: {}
  config:
    archive: null
    options: null
    storages: null
    storage_readers: null
    storage_writers: null
  results:
    scan_results:
    - id: "Linux:%2Fvar%2Frdoss-ort%2Fmnt:src:"
      results:
      - provenance:
          download_time: "1970-01-01T00:00:00Z"
        scanner:
          name: "ScanCode"
          version: "3.2.1-rc2"
          configuration: "--copyright --license --ignore *.ort.yml --info --strip-root\
            \ --timeout 300 --ignore HERE_NOTICE --ignore META-INF/DEPENDENCIES --json-pp"
        summary:
          start_time: "2020-10-27T05:10:32.326942Z"
          end_time: "2020-10-27T05:11:46.008730Z"
          file_count: 0
          package_verification_code: "da39a3ee5e6b4b0d3255bfef95601890afd80709"
          licenses: []
          copyrights: []
        raw_result:
          headers:
          - tool_name: "scancode-toolkit"
            tool_version: "3.2.1rc2"
            options:
              input:
              - "/var/rdoss-ort/mnt/src"
              "--copyright": true
              "--ignore":
              - "*.ort.yml"
              - "HERE_NOTICE"
              - "META-INF/DEPENDENCIES"
              "--info": true
              "--json-pp": "/var/rdoss-ort/mnt/native-scan-results/src_ScanCode.json"
              "--license": true
              "--processes": "3"
              "--strip-root": true
              "--timeout": "300.0"
            notice: "Generated with ScanCode and provided on an \"AS IS\" BASIS, WITHOUT\
              \ WARRANTIES\nOR CONDITIONS OF ANY KIND, either express or implied.\
              \ No content created from\nScanCode should be considered or used as\
              \ legal advice. Consult an Attorney\nfor any legal advice.\nScanCode\
              \ is a free software code scanning tool from nexB Inc. and others.\n\
              Visit https://github.com/nexB/scancode-toolkit/ for support and download."
            start_timestamp: "2020-10-27T051034.037029"
            end_timestamp: "2020-10-27T051144.979079"
            duration: 70.94207644462585
            message: null
            errors: []
            extra_data:
              files_count: 0
          files:
          - path: "src"
            type: "directory"
            name: "src"
            base_name: "src"
            extension: ""
            size: 0
            date: null
            sha1: null
            md5: null
            sha256: null
            mime_type: null
            file_type: null
            programming_language: null
            is_binary: false
            is_text: false
            is_archive: false
            is_media: false
            is_source: false
            is_script: false
            licenses: []
            license_expressions: []
            percentage_of_license_text: 0
            copyrights: []
            holders: []
            authors: []
            files_count: 0
            dirs_count: 0
            size_count: 0
            scan_errors: []
    storage_stats:
      num_reads: 0
      num_hits: 0
    has_issues: false
evaluator: null

```

Maybe I'm not making myself clear. From the above result, there's only `has_issues`, there is no `has_errors` at all.
