### ISSUE TITLE
Need a way to configure additional Copyright holders

### ISSUE THREAD

**Issue by sschuberth** [oss-review-toolkit/ort#3400]
While ORT has a way to [add custom license texts](https://github.com/oss-review-toolkit/ort/blob/master/docs/dir-custom-license-texts.md), the license text alone is of little value if you cannot also add custom Copyright holders.

Let's start a discussion where Copyright holders could be added / curated. My current thinking is to somehow allow to put them into `curations.yml` as they would then nicely pair with e.g. `concluded_license`. However, `curations.yml` is not designed to curate data that is not known to the analyzer.

As I'd really like to avoid adding yet another separate configuration file for *only* that purpose, maybe we could extend the curation concept also to the scanner, call the current `curations.yml` file `analyzer-curations.yml`, and create a new `scanner-curations.yml` file that can curate multiple aspects of a scan summary. This would then also nicely allow to curate e.g. false-positive license findings from the scanner.

@mnonnenmacher @fviernau any opinion here?

**Comment by tsteenbe** [comment]
As copyright holders normally associated with a license for it makes sense to make adding or curating copyright holders similar to how we do things for licenses e.g. [license finding curations](https://github.com/oss-review-toolkit/ort/blob/master/docs/config-file-ort-yml.md#curations) where we enable ORT users to add / curate license found by the scanner.

My first thoughts below:

 **.ort.yml / package configuration copyright holder curation (fix a finding)**

```
curations:
  license_findings:
  - path: "src/main.cpp"
    start_lines: "3"
    line_count: 11
    detected_license: "GPL-2.0-only"
    reason: "CODE"
    comment: "The scanner matches a variable named `gpl`."
    concluded_license: "Apache-2.0"
  copyright_findings:
  - path: "src/main.cpp"
    start_lines: "2"
    line_count: 1
    detected_copyright: "Copyright 2000-$ build.year a http://www.apache.org/ Apache Software Foundation"
    reason: "VARIABLE"
    comment: "Copyright line contains variable."
    concluded_copyrights:
    - "Copyright 2000-2016 Apache Software Foundation"
```

**ort.yml / package configuration copyright holder(s) addition (add a holder)**

```
curations:
  copyright_findings:
  - path: "src/main.cpp"
    start_lines: "2"
    reason: MISSING
    comment: "Maintainer forgot to add copyright statement, found the applicable holders on the project website at http://..."
    concluded_copyrights:
    - "Copyright 2000-2016 Apache Software Foundation"
    - "Copyright 2015 HERE Europe B.V."
```

**.ort.yml / package configuration copyright removal (remove a false finding for single review/package instead of using copyright-grab)**

```
curations:
  copyright_findings:
  - path: "src/main.cpp"
    start_lines: "2"
    detected_copyright: "(c), Ao a Au"
    reason: INCORRECT
    comment: "Garbage copyright finding"
    concluded_copyrights:
    - ""
```
