### ISSUE TITLE
Support referring to external SPDX files from project.spdx.yml

### ISSUE THREAD

**Issue by sschuberth** [oss-review-toolkit/ort#3402]
When multiple projects with a [project.spdx.yml](https://github.com/oss-review-toolkit/ort/blob/master/analyzer/src/funTest/assets/projects/synthetic/spdx/project/project.spdx.yml) file each refer to the same packages, it can be beneficial to move out declarations of packages (like [cURL in this example](https://github.com/oss-review-toolkit/ort/blob/24905dc5234e22dda35188a4f5d18371270998b1/analyzer/src/funTest/assets/projects/synthetic/spdx/project/project.spdx.yml#L25-L38)) to external files to avoid duplication.

We should come up with both an example on how to do that from an SPDX syntax perspective, and add support for it in [SpdxDocumentFile](https://github.com/oss-review-toolkit/ort/blob/master/analyzer/src/main/kotlin/managers/SpdxDocumentFile.kt).

@tsteenbe can you help with the example?

**Comment by neubs-bsi** [comment]
I would propose the following example, based mostly the [project.spdx.xml](https://github.com/oss-review-toolkit/ort/blob/master/analyzer/src/funTest/assets/projects/synthetic/spdx/project/project.spdx.yml) from the ORT functional tests and validated with the [spdx java cli tool](https://github.com/spdx/tools-java.git):

```

SPDXID: "SPDXRef-DOCUMENT"
spdxVersion: "SPDX-2.2"
creationInfo:
  created: "2020-07-23T18:30:22Z"
  creators:
  - "Organization: Example Inc."
  - "Person: Max Mustermann"
  licenseListVersion: "3.9"
name: "xyz-0.1.0"
dataLicense: "CC0-1.0"
documentNamespace: "http://spdx.org/spdxdocs/spdx-document-xyz"
documentDescribes:
- "SPDXRef-Package-xyz"
externalDocumentRefs:
- externalDocumentId: "DocumentRef-curl-7.70.0"
  checksum:
    algorithm: "SHA1"
    checksumValue: "a2ab98f8e10bad892313ccc573b3820369551dcb"
  spdxDocument: "https://github.com/oss-review-toolkit/ort/blob/master/analyzer/src/funTest/assets/projects/synthetic/spdx/package/libs/curl/package.spdx.yml"
packages:
- SPDXID: "SPDXRef-Package-xyz"
  description: "Awesome product created by Example Inc."
  copyrightText: "Copyright (C) 2020 Example Inc."
  downloadLocation: "git+ssh://gitlab.example.com:3389/products/xyz.git@b2c358080011af6a366d2512a25a379fbe7b1f78"
  filesAnalyzed: false
  homepage: "https://example.com/products/xyz"
  licenseConcluded:  "NOASSERTION"
  licenseDeclared: "Apache-2.0 AND curl AND LicenseRef-Proprietary-ExampleInc"
  name: "xyz"
  versionInfo: "0.1.0"
- SPDXID: "SPDXRef-Package-openssl"
  description: "OpenSSL is a robust, commercial-grade, full-featured Open Source Toolkit for the Transport Layer Security (TLS) protocol formerly known as the Secure Sockets Layer (SSL) protocol. The protocol implementation is based on a full-strength general purpose cryptographic library, which can also be used stand-alone."
  copyrightText: "copyright 2004-2020 The OpenSSL Project Authors. All Rights Reserved."
  downloadLocation: "git+ssh://github.com/openssl/openssl.git@e2e09d9fba1187f8d6aafaa34d4172f56f1ffb72"
  filesAnalyzed: false
  homepage: "https://www.openssl.org/"
  licenseConcluded: "NOASSERTION"
  licenseDeclared: "Apache-2.0"
  packageFileName: "./libs/openssl"
  name: "openssl"
  versionInfo: "1.1.1g"
relationships:
- spdxElementId: "SPDXRef-DOCUMENT"
  relatedSpdxElement: "SPDXRef-Package-xyz"
  relationshipType: "DESCRIBES"
- spdxElementId: "SPDXRef-Package-xyz"
  relatedSpdxElement: "DocumentRef-curl-7.70.0:SPDXRef-ToolsElement"
  relationshipType: "DEPENDS_ON"
- spdxElementId: "SPDXRef-Package-xyz"
  relatedSpdxElement: "SPDXRef-Package-openssl"
  relationshipType: "DEPENDS_ON"

```

@tsteenbe I would be glad to hear your feedback to the suggested example. 

The spdx data model of ORT already contains all the data fields, just doesn't process the information. This functionality would need to be added.
