### ISSUE TITLE
Analyzer combines multiple licenses using AND. The actual operator is ignored

### ISSUE THREAD

**Issue by MarcelBochtler** [oss-review-toolkit/ort#3524]
All detected dependencies are currently combined using the SpdxOperator `AND`.

https://github.com/oss-review-toolkit/ort/blob/4be3ab1fbac441ae07fbc8f3f8399582975c0020/utils/src/main/kotlin/DeclaredLicenseProcessor.kt#L104-L106

This ignores the actual correct declaration in the Metadata.

e.g. h2database declares `MPL 2.0 or EPL 1.0`
```xml
<project>
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.h2database</groupId>
    <artifactId>h2</artifactId>
    <version>1.4.200</version>
    <packaging>jar</packaging>
    <name>H2 Database Engine</name>
    <url>https://h2database.com</url>
    <description>H2 Database Engine</description>
    <licenses>
        <license>
            <name>MPL 2.0 or EPL 1.0</name>
            <url>https://h2database.com/html/license.html</url>
            <distribution>repo</distribution>
        </license>
    </licenses>
    <scm>
        <connection>scm:git:https://github.com/h2database/h2database</connection>
        <url>https://github.com/h2database/h2database</url>
    </scm>
    <developers>
        <developer>
            <id>thomas.tom.mueller</id>
            <name>Thomas Mueller</name>
            <email>thomas.tom.mueller at gmail dot com</email>
        </developer>
    </developers>
    <dependencies>
    </dependencies>
</project>
```

The analyzer's result looks like that:
```yml
  result:
    projects:
    - id: "Maven:com.h2database:h2:1.4.201-SNAPSHOT"
      definition_file_path: "h2/pom.xml"
      declared_licenses:
      - "EPL 1.0"
      - "MPL 2.0"
      declared_licenses_processed:
        spdx_expression: "EPL-1.0 AND MPL-2.0"
        mapped:
          EPL 1.0: "EPL-1.0"
          MPL 2.0: "MPL-2.0"
```
