### ISSUE TITLE
Allow excluding a specific dependency

### ISSUE THREAD

**Issue by tsteenbe** [oss-review-toolkit/ort#3537]
Not all package manager have scopes such as Python where its `requirements.txt` is basically a flat list of dependencies. What if in https://github.com/heremaps/xyz-spaces-python/blob/master/requirements.txt the developer was to exclude [geopandas](https://geopandas.org/) as [PROVIDED_BY](https://github.com/oss-review-toolkit/ort/blob/master/model/src/main/kotlin/config/PathExcludeReason.kt#L63) e.g. be provided by end user or to be installed on the system.

Propose we introduce way for ORT users to exclude a specific package and was thinking of below:

```
---
excludes:
  paths:
  - pattern: "requirements_dev.txt"
    reason: "BUILD_TOOL_OF"
    comment: "Optional dependencies only used for development / testing."
  - pattern: "tests/**"
    reason: "TEST_OF"
    comment: "Directory only used for testing."
  dependencies:
  // Pattern matches the id of the package, ommitting the version number here so it will always match the package 
  - pattern: "PyPI::geopandas"
    reason: "PROVIDED_BY"
    comment: "Packages to be provided at runtime by user."
```
