### ISSUE TITLE
Web App report's tables show incorrect information

### ISSUE THREAD

**Issue by mmurto** [oss-review-toolkit/ort#4180]
The tables in Web App report show wrong package/error information. Here's four issues from evaluation result and the html report and web app report that they generate. The packages shown in Web App don't match those in the result file and html report.

```yml
  - rule: "UNMAPPED_DECLARED_LICENSE"
    pkg: "Maven:antlr:antlr:2.7.7"
    license: null
    license_source: null
    severity: "WARNING"
    message: "The declared license 'BSD License' could not be mapped to a valid license\
      \ or parsed as an SPDX expression. The license was found in package Maven:antlr:antlr:2.7.7."
    how_to_fix: "A text written in MarkDown to help users resolve policy violations\n\
      which may link to additional resources."
  - rule: "UNMAPPED_DECLARED_LICENSE"
    pkg: "Maven:jaxen:jaxen:1.2.0"
    license: null
    license_source: null
    severity: "WARNING"
    message: "The declared license 'BSD License 2.0' could not be mapped to a valid\
      \ license or parsed as an SPDX expression. The license was found in package\
      \ Maven:jaxen:jaxen:1.2.0."
    how_to_fix: "A text written in MarkDown to help users resolve policy violations\n\
      which may link to additional resources."
  - rule: "UNMAPPED_DECLARED_LICENSE"
    pkg: "Maven:org.codehaus.woodstox:stax2-api:4.2"
    license: null
    license_source: null
    severity: "WARNING"
    message: "The declared license 'The BSD License' could not be mapped to a valid\
      \ license or parsed as an SPDX expression. The license was found in package\
      \ Maven:org.codehaus.woodstox:stax2-api:4.2."
    how_to_fix: "A text written in MarkDown to help users resolve policy violations\n\
      which may link to additional resources."
  - rule: "UNMAPPED_DECLARED_LICENSE"
    pkg: "Maven:org.codehaus.woodstox:stax2-api:4.2.1"
    license: null
    license_source: null
    severity: "WARNING"
    message: "The declared license 'The BSD License' could not be mapped to a valid\
      \ license or parsed as an SPDX expression. The license was found in package\
      \ Maven:org.codehaus.woodstox:stax2-api:4.2.1."
    how_to_fix: "A text written in MarkDown to help users resolve policy violations\n\
      which may link to additional resources."
```

![html-report](https://user-images.githubusercontent.com/2370887/122236948-9c3d2a00-cec7-11eb-988d-851ff0aee880.png)

![webapp-report](https://user-images.githubusercontent.com/2370887/122237076-b414ae00-cec7-11eb-8511-868502ed1e63.png)
