### ISSUE TITLE
Curation.yml Configuration Capability Enhancement Request

### ISSUE THREAD

**Issue by porsche-rishisaxena** [oss-review-toolkit/ort#4379]
**Description:** 
During the analysis, we found there are multiple ways of curating license(s) using either curation.yml or .ort.yml. Can "License Finding", "Policy Rule Violation" and "License Choices" also be part of curation.yml as well?

**Reason:** 
As the developers are not aware of the license model(s) and what to curate, this is a dedicated responsibility of curation team in conjunction with Legal team which will allow curation team to configure the license finding using Curation.yml

**Understanding:**
If there is already a way to conclude multiple licenses in Curation.yml, then we would like to understand how?

**Proposal:**
![curation-config](https://user-images.githubusercontent.com/87651181/130218890-11ceaa08-0ead-4bb6-95fa-bc0c84f8d901.PNG)

**Comment by MarcelBochtler** [comment]
Hi @porsche-rishisaxena, do I understand you correctly that you differentiate between the _project-local_ `.ort.yml` and an ORT-global configuration possibilty?
Or is it really important for you that the `curations.yml` is being used?

**License Choices**
License choices for the `.ort.yml` were implemented in [this PR](https://github.com/oss-review-toolkit/ort/pull/3801) (for reference).
In discussions in the [corresponding issues](https://github.com/oss-review-toolkit/ort/issues/3396) we were already talking / planning to provide `global` license choices. But this is not yet implemented.
IMO this shouldn't be done in a `curations.yml` but rather in a separate `licenseChoices.yml`.

**Resolutions**
Can already be set globally: https://github.com/oss-review-toolkit/ort/blob/master/docs/config-file-resolutions-yml.md.

**License finding curations**
Can be set globally using package-configurations: https://github.com/oss-review-toolkit/ort/blob/master/docs/config-file-package-configuration-yml.md.

**Comment by MarcelBochtler** [comment]
> Understanding:
> If there is already a way to conclude multiple licenses in Curation.yml, then we would like to understand how?

Not sure if I understand this correctly. You can conclude one SPDX license expression per package ID.

You can either conclude licenses for every package in a single `curations.yml` file and use ORT's analyzer with `--package-curations-file`
```yaml
- id: "Maven:com.example:package:1.2.3"
  curations:
    comment: |
      Example curation
    concluded_license: "(GPL-2.0-only OR MIT) AND Apache-2.0"

- id: "Maven:org.oss-review-tookit:another-package:0.0.0"
  curations:
    comment: |
      Another example curation
    concluded_license: "Apache-2.0"
```

Or use multiple `yaml`-files in a directory structure using ORT's analyzer option: `--package-curations-dir`
(the helper-cli has a function to create curations in this directory structure: https://github.com/oss-review-toolkit/ort/blob/master/helper-cli/src/main/kotlin/commands/packagecuration/CreateCommand.kt)
