### ISSUE TITLE
Using ORT with repo or submodules

### ISSUE THREAD

**Issue by tardyp** [oss-review-toolkit/ort#4505]
Here at Renault, most of our integration is made with repositories aggregated with [google repo](https://github.com/grouperenault/gitrepo) or git submodules.

We do put tags on our releases, but we would like to test our mainlines before. We started to use a bit of conan, but we can't wait this process to finish to implement full open-source reviews. 

At the moment we have been using scancode-toolkit to scan our code, and have some custom report aggregation on google datastudio. We are happy with that but are starting to hit the problems that ort.yml is resolving. (exclude, curation, resolutions, license-choices)

We are struggling to use the OSS review toolkit because it all starts with a package manager, and we don't have one.

We tried to generate a spdx BOM from our repo list, or to generate the intermediate analyser output, but then the downloader seems to insist in downloading a tag and will just not accept to use a mainline branch for scan input.

So if my analysis is good, we would need to features on ORT

- a new Analyser which takes a list of (package_name, repository_url, repository_branch) tuples and just output that lists in the analyser output format. We do intent to generate this format externally with internal tools we already have. That analyser input would be more simple than the analyser output and also have more stability.
- Fix in the downloader to be able to download from a branch and not only a tag.

We are willing to help on the development of those features as needed, but will probably need some architecture help to make sure we are making the right change

Thanks for your inputs!

**Comment by sschuberth** [comment]
> We are struggling to use the OSS review toolkit because it all starts with a package manager, and we don't have one.
> 
> We tried to generate a spdx BOM from our repo list

Using the [SPDX "package manager"](https://github.com/oss-review-toolkit/ort#analyzer-for-spdx-documents) as a fallback is actually the right approach in this case.

> the downloader seems to insist in downloading a tag and will just not accept to use a mainline branch for scan input.

That should not be the case if you configure ORT to [allow dynamic versions](https://github.com/oss-review-toolkit/ort/blob/eaccacc5ec309fa4a25236e377ca5772d334719d/model/src/main/resources/reference.conf#L14) (which is disabled by default as it prevents deterministic scan results for a given revision).

> We are willing to help on the development of those features as needed, but will probably need some architecture help to make sure we are making the right change

Glad to hear you're willing to contribute! For architecture help you might want to join the bi-weekly [Developer Meeting](https://github.com/oss-review-toolkit/ort/wiki/Developer-Meeting). Ping me on [Slack](https://join.slack.com/t/ort-talk/shared_invite/enQtMzk3MDU5Njk0Njc1LThiNmJmMjc5YWUxZTU4OGI5NmY3YTFlZWM5YTliZmY5ODc0MGMyOWIwYmRiZWFmNGMzOWY2NzVhYTI0NTJkNmY) for an invite.

**Comment by tsteenbe** [comment]
@tardyp  At HERE Technologies we have several google repo-based projects that we have been scanning with ORT for the past 5+ years.  We call ORT's downloader  to checkout the git-repo project in a scan and then pass the dir to the analyzer, scanner, evaluator and reporter. ORT will then report the the root package as Unmanaged but then we use package.spdx.yml to defined included OSS packages.

Happy to give you a demo (ping me on ORT slack/email me to arrange a date) and then we can discuss any needed features in detail.

**Comment by tardyp** [comment]
Hello @sschuberth  and @tsteenbe , thanks for your kind answers.

I am happy to learn that actually my use cases are supported already.
I'd like to keep the spdx input as our repo source are quite big and we have some tooling already to manage them which we would like to reuse.

So I have still been struggling to generate a spdx file that is accepted by ort analyser.
I eventually just setup a simplified example for public discussion

```
SPDXID: SPDXRef-DOCUMENT
creationInfo:
  created: '2020-07-23T18:30:22Z'
  creators:
  - oss-scanner
  licenseListVersion: '3.9'
dataLicense: Apache
documentDescribes:
- SPDXRef-Package-proj1
documentNamespace: http://spdx.org/spdxdocs/spdx-document-proj1
name: proj1
packages:
- SPDXID: SPDXRef-Package-proj1
  copyrightText: Copyright (C) 2020 Example Inc.
  description: proj1
  downloadLocation: git+https://github.com/tardyp/proj1@main
  filesAnalyzed: false
  licenseConcluded: NOASSERTION
  licenseDeclared: NOASSERTION
  name: proj1
  versionInfo: main
- SPDXID: SPDXRef-Package-proj2
  copyrightText: Copyright (C) 2020 Example Inc.
  description: proj2
  downloadLocation: git+https://github.com/tardyp/proj1@main
  filesAnalyzed: false
  licenseConcluded: NOASSERTION
  licenseDeclared: NOASSERTION
  name: proj2
  versionInfo: main
relationships:
- relatedSpdxElement: SPDXRef-Package-proj1
  relationshipType: DEPENDENCY_OF
  spdxElementId: SPDXRef-Package-proj2
spdxVersion: SPDX-2.2
```

A first trivial remark: copyrightText is mandatory. I don't have this info, that's why I need a scan run. This should be optional
 
Then relationshipType has to be DEPENDENCY_OF. I wasn't able to find a relationship mode that actually translate the relationship to  something that appears in analyzer-result.yml

last the resulting analyser do not take in account the downloadLocation of the main package, vcs info for that main package is empty.

```yaml
repository:
  vcs:
    type: ""
    url: ""
    revision: ""
    path: ""
  vcs_processed:
    type: ""
    url: ""
    revision: ""
    path: ""
  config: {}
analyzer:
  start_time: "2021-09-30T19:11:44.896295Z"
  end_time: "2021-09-30T19:11:45.455184Z"
  environment:
    ort_version: "3ac5b46-dirty"
    java_version: "11.0.10"
    os: "Mac OS X"
    processors: 8
    max_memory: 2147483648
    variables:
      SHELL: "/bin/zsh"
      TERM: "xterm-256color"
      JAVA_HOME: "/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/"
      GOPATH: "/Users/<>/go"
    tool_versions: {}
  config:
    ignore_tool_versions: false
    allow_dynamic_versions: true
  result:
    projects:
    - id: "SpdxDocumentFile::proj1:main"
      definition_file_path: ""
      declared_licenses:
      - "NOASSERTION"
      declared_licenses_processed:
        spdx_expression: "NOASSERTION"
      vcs:
        type: ""
        url: ""
        revision: ""
        path: ""
      vcs_processed:
        type: ""
        url: ""
        revision: ""
        path: ""
      homepage_url: ""
      scope_names:
      - "default"
    packages:
    - package:
        id: "SpdxDocumentFile::proj2:main"
        purl: "pkg:spdxdocumentfile/proj2@main"
        declared_licenses:
        - "NOASSERTION"
        declared_licenses_processed:
          spdx_expression: "NOASSERTION"
        description: "proj2"
        homepage_url: ""
        binary_artifact:
          url: ""
          hash:
            value: ""
            algorithm: ""
        source_artifact:
          url: ""
          hash:
            value: ""
            algorithm: ""
        vcs:
          type: "Git"
          url: "https://github.com/tardyp/proj1"
          revision: "main"
          path: ""
        vcs_processed:
          type: "Git"
          url: "https://github.com/tardyp/proj1.git"
          revision: "main"
          path: ""
      curations: []
    dependency_graphs:
      SpdxDocumentFile:
        packages:
        - "SpdxDocumentFile::proj2:main"
        scopes:
          :proj1:main:default:
          - root: 0
        nodes:
        - {}
        edges: []
    has_issues: false
scanner: null
advisor: null
evaluator: null
```

The scanner then will fail to scan anything as it can't find the source of the main package.


thoughts?
