### ISSUE TITLE
Allow to curate copyrights directly (not via authors)

### ISSUE THREAD

**Issue by sschuberth** [oss-review-toolkit/ort#4519]
> adding the Copyright holder statements to the org.ossreviewtoolkit.model.PackageCurationData entity

FYI, I just pushed my local [`curate-copyrights` branch](https://github.com/oss-review-toolkit/ort/tree/curate-copyrights) which trivially starts doing that.

@rbieniek do you want to take over that branch of mine?

_Originally posted by @sschuberth in https://github.com/oss-review-toolkit/ort/issues/4463#issuecomment-931138189_

**Comment by sschuberth** [comment]
> @rbieniek do you want to take over that branch of mine?

Ping @porsche-rbieniek and @porsche-rishisaxena as a reminder to move this forward.

**Comment by porsche-rbieniek** [comment]
Porsche solution submitted as https://github.com/oss-review-toolkit/ort/pull/5315

**Comment by sschuberth** [comment]
> Porsche solution submitted as #5315

Please associate issues with PRs by using one of the respective [keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) in one of the commits in the PR instead of manually adding comments.

**Comment by tsteenbe** [comment]
Copy-paste from [July 14th, 2022 ORT developer meeting minutes](https://github.com/oss-review-toolkit/ort/wiki/Developer-Meeting#2022-07-14) in which we had a discussion on how to implement curating declared copyrights 

**A. Use curations to fix-up curate copyrights**

The declared copyrights comes package metadata collected by ORT _analyzer_ which can be fixed up using curations.
Note that a lot of package managers do not have copyrights fields only author, contributors, developers which in some case are "mis-used" to convey copyright information. We could implement a parseCopyrights() to from parseAuthors() find copyright statements e.g. entries starting with "copyright" or "(c)"

Below several ideas for how curating declared licenses in curations.yml could look like.

Remove a declared copyright

```
declared_copyright_mapping:
   "MIT": ""
```

Add a declared copyright

```
declared_copyright_mapping:
   "": "Copyright (C) 2022 John Doe"
```

Overwrite all declared copyrights with a single one:

```
declared_copyright_mapping:
   "*": ""
   "": "Copyright (C) 2022 John Doe"
```

Overwrite all declared copyrights with a more than one:

```
declared_copyright_mapping:
   "*": ""
   "": "Copyright (C) 2022 John Doe"
   "": "Copyright (C) 2019 Jane Doe"
   "": "Copyright (C) 2012 Example, Inc"
```

Associate declared licenses with declared copyrights:

```
declared_license_copyrights_mapping:
   "MIT": "Copyright (C) 2022 John Doe"
   "MIT": "Copyright (C) 2019 Jane Doe"
   "Apache-2.0": "Copyright (C) 2012 Example, Inc"
```

**B. Use package configurations to curate detected copyrights**

Introduce a `copyright_finding_curation` in package configurations to curate detected copyrights:

```
id: "NPM::ansi-styles:4.2.1"
copyright_finding_curations:
  - path: "README.md"
    start_lines: "3"
    line_count: 11
    detected_copyright: ""
    reason: "INCORRECT"
    comment: "Copyright only written on project website."
    concluded_copyright: "Copyright (C) 2022 John Doe"
```

d. Associate detected licenses to detected copyrights in a package configuration

```
id: "NPM::ansi-styles:4.2.1"
license_copyright_finding_curation:
  - license: "MIT"
    copyrights:
       - "Copyright (C) 2022 John Doe"
       - "Copyright (C) 2019 Jane Doe"
       - "Copyright (C) 2012 Example, Inc."
```

**C. Use concluded copyright to overwrite both declared and detected**

Introduce the concept of a concluded copyright? Should we introduce this, believe `concluded_license` should be removed from curations as it applies to both declared and detected licenses

```
concluded_copyright: "Copyright (C) 2022 John Doe"
```
