### ISSUE TITLE
how curations work with the scanner and reporter

### ISSUE THREAD

**Issue by martencassel** [oss-review-toolkit/ort#4542]
I have written two curations for 2 go packages, and the analyzer have detected them.
When i run the scanner it will incorrectly find these licenses.
But the reporter will write these incorrect license findings.
My goal is to fix these two incorrect license findings with the curation file, 
i would like that my NOTICE file should reflect this.
What do i need to do to fix this ?

**Comment by sschuberth** [comment]
Could you please copy & paste your curations here?

**Comment by martencassel** [comment]
```bash
cat ~/.ort/config/curations.yml 
- id: "GoMod::github.com/spf13/pflag:v1.0.5"
  curations:
    comment: >-
      The package is licensed under BSD-3-Clause"
    concluded_license: "BSD-3-Clause"

- id: "GoMod::github.com/gorilla/mux:v1.8.0"
  curations:
    comment: >-
      The package is licensed under BSD-3-Clause"
    concluded_license: "BSD-3-Clause"
```

**Comment by martencassel** [comment]
```
analyzer:
  start_time: "2021-10-05T08:19:38.662978Z"
  end_time: "2021-10-05T08:20:05.204154Z"
  environment:
    ort_version: "DOCKER-SNAPSHOT"
    java_version: "11.0.8"
    os: "Linux"
    processors: 8
    max_memory: 6297747456
    tool_versions:
      GoMod: "1.16.5"
```
