### ISSUE TITLE
Applying package curations may lead to loosing data from VCS processed

### ISSUE THREAD

**Issue by fviernau** [oss-review-toolkit/ort#4618]
`PackageCurationData.apply()` applies the VCS curations to `Package.vcs`, not `Package.vcsProcessed` [1]. So, the `vcsProcessed` gets set to `vcs.normalize()` [2]. So, if `vcsProcessed` was created in any non-default way, the information it represents always gets lost. For example several package managers incorporate the fallback URLs only into `vcsProcessed`, see e.g. [3]. So, a VCS curation for Maven artifacts always lead to loosing the the VCS info if it was created from the fallback URL.

**Example**

package:
```
- package:
      id: "Maven:org.aspectj:aspectjrt:1.9.6"
      ... 
       vcs:
          type: ""
          url: ""
          revision: ""
          path: ""
        vcs_processed:
          type: "Git"
          url: "https://github.com/eclipse/org.aspectj.git"
          revision: ""
          path: ""
      curations: []
```
package curation:
```
- id: "Maven:org.aspectj:aspectjrt"
  curations:
    comment: "Package resides in its own directory within repo."
    vcs:
      path: "runtime"
```
Applying above curation to above package leads to a package with:
```
       vcs:
          type: ""
          url: ""
          revision: ""
          path: "runtime"
        vcs_processed:
          type: ""
          url: ""
          revision: "runtime"
          path: ""
```

[1] https://github.com/oss-review-toolkit/ort/blob/971292669a7820e1d749dc24582e0c0aca76649d/model/src/main/kotlin/PackageCurationData.kt#L105-L116
[2] https://github.com/oss-review-toolkit/ort/blob/971292669a7820e1d749dc24582e0c0aca76649d/model/src/main/kotlin/Package.kt#L108
[3] https://github.com/oss-review-toolkit/ort/blob/971292669a7820e1d749dc24582e0c0aca76649d/analyzer/src/main/kotlin/managers/utils/MavenSupport.kt#L647-L649
