### ISSUE TITLE
git-repo: Add the manifest path to the URL instead of the VCS path

### ISSUE THREAD

**Issue by mnonnenmacher** [oss-review-toolkit/ort#4741]
Currently the [VCS path](https://github.com/oss-review-toolkit/ort/blob/de72b7ad8e77f169d517e46ed15ccbe23d4a9f79/model/src/main/kotlin/VcsInfo.kt#L55-L60) has a special meaning for git-repo: Instead of the path inside of the repository it defines the path to the manifest file. This requires to consider this special meaning in many placing working with the VCS path. For example, this complicates the handling of provenances.

The proposal to fix this is to append the manifest path to the URL instead of putting it into the path property. This way only the `GitRepo` implementation needs to know about the meaning and all other places can consistently handle the path property.

With this proposal this VCS info:
```yaml
vcs:
  type: "git-repo"
  url: "https://example.com/repo.git"
  revision: "some_revision"
  path: "manifest.xml"
```

Would become this:
```yaml
vcs:
  type: "git-repo"
  url: "https://example.com/repo.git?manifest.xml"
  revision: "some_revision"
  path: ""
```

Not the for Maven POM files we already support the proposed syntax, but have to translate it to the way we currently handle manifest paths:
https://github.com/oss-review-toolkit/ort/blob/ea2f48305fead9b1c11d2f3a3963c6981d0378dc/analyzer/src/main/kotlin/managers/utils/MavenSupport.kt#L203-L213

**Comment by tsteenbe** [comment]
@mnonnenmacher  Instead of using a `?` I propose we use a `#` so ORT is aligned with both https://spdx.github.io/spdx-spec/v2-draft/package-information/#77-package-download-location-field and https://github.com/package-url/purl-spec#purl

**Comment by sschuberth** [comment]
I believe quoting the PURL spec here is wrong, as the `#subpath` is documented as an "extra subpath *within* a package, relative to the package root". That is, `#subpath` exactly is what our `VcsInfo.path` is. In PURL, we'd probably model the path to the *manifest* as a qualifier, just like in @mnonnenmacher's proposal; however, I believe we should use an explicit name, like `?manifest=manifest.xml`.

**Comment by pombredanne** [comment]
Just out of curiosity, as my purl antennas caught a signal here ;) , do you have a concrete example using real data rather than the mock data below?
```
vcs:
  type: "git-repo"
  url: "https://example.com/repo.git"
  revision: "some_revision"
  path: "manifest.xml"
```

**Comment by sschuberth** [comment]
@pombredanne, you could use [this manifest](https://github.com/oss-review-toolkit/ort-test-data-git-repo/blob/master/manifest.xml), i.e.

```
vcs:
  type: "git-repo"
  url: "https://github.com/oss-review-toolkit/ort-test-data-git-repo.git"
  revision: "31588aa8f8555474e1c3c66a359ec99e4cd4b1fa"
  path: "manifest.xml"
```

(In the current syntax.)
