### ISSUE TITLE
Timeouts for the Package: com.azure:azure-core-http-netty:1.5.0

### ISSUE THREAD

**Issue by schvvarzekatze** [oss-review-toolkit/ort#4988]
I still get timeouts after 300 seconds for some `json` files of the package `com.azure:azure-core-http-netty:1.5.0`  : 
`ERROR: Timeout after 300 seconds while scanning file 'sdk/compute/mgmt/src/test/resources/session-records/canListVirtualMachineImages.json'.`

It did not help to run the reporter with `--package-configuration-file` and the follwing path exclude:
```
- id: "Maven:com.azure:azure-core-http-netty:1.5.0"
  source_artifact_url: "https://repo.maven.apache.org/maven2/com/azure/azure-core-http-netty/1.5.0/azure-core-http-netty-1.5.0-sources.jar"
  path_excludes:
    - pattern: "*/test/*"
      reason: "TEST_OF"
      comment: "This directory contains tests which is not distributed."
```

What is the best way to fix it? Does it help to change the timeout configuration?

Thank you very much for your help.

**Comment by schvvarzekatze** [comment]
I only found out to change the `.ort.yml` config as a workaround. The packages refered by the timeout error seem not to be relevant for the license classification.
```
resolutions:
  issues:
    - message: "ERROR: Timeout after 300 seconds while scanning file 'sdk/compute/mgmt/src/test/resources/session-records/canListVirtualMachineImages.json'."
      reason: "SCANNER_ISSUE"
      comment: "The error can be ignored because the file does not contain relevant license information."
```
