### ISSUE TITLE
WebApp Reporter: License expressions from ScanCode should be displayed in report

### ISSUE THREAD

**Issue by MarcelBochtler** [oss-review-toolkit/ort#5017]
The `scan-result.yml` contains license findings with a choice for the jhipster package:
```yml
- license: "Apache-2.0 OR GPL-1.0-or-later"
  location:
    path: "META-INF/maven/io.github.jhipster/jhipster-framework/pom.xml"
    start_line: 21
    end_line: 24
- license: "Apache-2.0 OR GPL-2.0-or-later WITH Classpath-exception-2.0"
  location:
    path: "META-INF/maven/io.github.jhipster/jhipster-framework/pom.xml"
    start_line: 18
  end_line: 21
```

The WebApp reporter does not display these license choices:
![SCR-20220202-nzp](https://user-images.githubusercontent.com/4022103/152193710-cac30589-cdd3-4737-a90b-f005449530ec.png)
