### ISSUE TITLE
Add the concept of "trusted" vendors / frameworks / SDKs

### ISSUE THREAD

**Issue by sschuberth** [oss-review-toolkit/ort#5105]
When scanning code for e.g. Android or iOS apps, there are some reoccurring fundamental SDK dependencies which usually contains a *lot* of source code. It makes little sense to scan these dependencies over and over again for (small) version changes.

To address the issue, I believe it's fair to assume that if a company decided to develop e.g. Android / iOS apps, the (business) decision to accept the use of the *required* SDKs has effectively already been made. With that in mind, it would be nice if ORT had a concept of "trusted vendors" where a copyright holder and license need to be specified for whole SDK / framework, and then scanning for all belonging / matching packages would be skipped.

This is conceptually similar to the existing mechanism of curating `authors` and `concludedLicense` in conjunction with enabling `skipConcluded`. A reason why this existing mechanism is not sufficient is that curations can only use ranges / wildcards as part of the `version`. However, in order to trust e.g. the Amazon AWS SDK as a whole, which includes a component like `Maven:com.amazonaws:aws-java-sdk-models:1.12.162`, we'd also need to allow wildcards for the `name` (at least), so that `authors` and `concludedLicense` could be curated for something like `Maven:com.amazonaws:aws-*:*`.

So a proposal to support the concept of "trusted" vendors / frameworks / SDKs would be to extend the curation logic to also accept wildcards / regexes for the `name`.

**Comment by sschuberth** [comment]
Another proposal just came to my mind: "Trusted" in this context should mean that we trust the *declared* license, and thus also do not need to scan to get the detected licenses, even if no explicit concluded license is present.

**Comment by sschuberth** [comment]
It has slipped my mind that we already [support the name of a package curation to be empty](https://github.com/oss-review-toolkit/ort/blob/034eba71f22d391efde8ac3551ffbc7a0d495801/model/src/main/kotlin/PackageCuration.kt#L53), so we can conclude the license (and author) for whole namespaces like `Maven:com.amazonaws` or `Maven:com.android.tools`.

So, it that mechanism maybe already good enough?

Note that this would still require separate curations for e.g. `Maven:com.google.android.datatransport` and `Maven:com.google.android.gms` etc., and we could not say `Maven:com.google.android.gms.*` (or similar).

**Comment by sschuberth** [comment]
> So, it that mechanism maybe already good enough?

I believe yes. Also see https://github.com/oss-review-toolkit/ort/pull/5971.

**Comment by sschuberth** [comment]
> > So, it that mechanism maybe already good enough?
> 
> I believe yes. Also see #5971.

Turns out that curations with empty name / version are not enough to fully support this use-case, so I'm reopening this.

A problem arises e.g. with NuGet packages which generally don't have a `namespace` as part of their `id`. See for example this list of ids:

- id: "NuGet::System.AppContext:4.1.0"
- id: "NuGet::System.Buffers:4.0.0"
- id: "NuGet::System.Collections:4.0.11"
- id: "NuGet::System.ComponentModel:4.0.1"
- id: "NuGet::System.Console:4.0.0"
- id: "NuGet::System.Diagnostics.Contracts:4.0.1"
- id: "NuGet::System.Dynamic.Runtime:4.0.11"
- ...

The actual goal would be to conclude the license and set the author for all "System" packages. Having individual curations, even with empty versions, is not feasible as there are a lot of these packages. Also, leaving both the name and version empty is no option, as that would result in `NuGet:::` which would match *all* NuGet `id`s, also non-"System" ones.

So we would either need to
- still support wildcards or regex for the name / version as proposed initially, or
- for the specific case of NuGet [treat parts of the name as the namespace](https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-namespaces).

**Comment by MarcelReiter** [comment]
Commenting here to support the "The current curation mechanism isn't enough" statement with an example of my current project.

For my Android-App i'd like to trust all `androidx.*` and `org.jetbrains.*` dependencies.
In an optimal world, that would be two curations, but without wildcards it's quite a bit more 😅

```
    - id: "Maven:androidx.activity"
      curations:
        authors:
          - "The Android Open Source Project"
        concluded_license: "Apache-2.0"

    - id: "Maven:androidx.annotation"
      curations:
        authors:
          - "The Android Open Source Project"
        concluded_license: "Apache-2.0"

    - id: "Maven:androidx.appcompat"
      curations:
        authors:
          - "The Android Open Source Project"
        concluded_license: "Apache-2.0"

    - id: "Maven:androidx.arch.core"
      curations:
        authors:
          - "The Android Open Source Project"
        concluded_license: "Apache-2.0"

    - id: "Maven:androidx.biometric"
      curations:
        authors:
          - "The Android Open Source Project"
        concluded_license: "Apache-2.0"

    - id: "Maven:androidx.camera"
      curations:
        authors:
          - "The Android Open Source Project"
        concluded_license: "Apache-2.0"

    - id: "Maven:androidx.cardview"
      curations:
        authors:
          - "The Android Open Source Project"
        concluded_license: "Apache-2.0"

    - id: "Maven:androidx.collection"
      curations:
        authors:
          - "The Android Open Source Project"
        concluded_license: "Apache-2.0"

    - id: "Maven:androidx.compose.animation"
      curations:
        authors:
          - "The Android Open Source Project"
        concluded_license: "Apache-2.0"

    - id: "Maven:androidx.compose.foundation"
      curations:
        authors:
          - "The Android Open Source Project"
        concluded_license: "Apache-2.0"

    - id: "Maven:androidx.compose.material"
      curations:
        authors:
          - "The Android Open Source Project"
        concluded_license: "Apache-2.0"

    - id: "Maven:androidx.compose.material3"
      curations:
        authors:
          - "The Android Open Source Project"
        concluded_license: "Apache-2.0"

    - id: "Maven:androidx.compose.runtime"
      curations:
        authors:
          - "The Android Open Source Project"
        concluded_license: "Apache-2.0"

    - id: "Maven:androidx.compose.ui"
      curations:
        authors:
          - "The Android Open Source Project"
        concluded_license: "Apache-2.0"

    - id: "Maven:androidx.concurrent"
      curations:
        authors:
          - "The Android Open Source Project"
        concluded_license: "Apache-2.0"

    - id: "Maven:androidx.constraintlayout"
      curations:
        authors:
          - "The Android Open Source Project"
        concluded_license: "Apache-2.0"

    - id: "Maven:androidx.coordinatorlayout"
      curations:
        authors:
          - "The Android Open Source Project"
        concluded_license: "Apache-2.0"

    - id: "Maven:androidx.core"
      curations:
        authors:
          - "The Android Open Source Project"
        concluded_license: "Apache-2.0"

    - id: "Maven:androidx.cursoradapter"
      curations:
        authors:
          - "The Android Open Source Project"
        concluded_license: "Apache-2.0"

    - id: "Maven:androidx.customview"
      curations:
        authors:
          - "The Android Open Source Project"
        concluded_license: "Apache-2.0"

    - id: "Maven:androidx.databinding"
      curations:
        authors:
          - "The Android Open Source Project"
        concluded_license: "Apache-2.0"

    - id: "Maven:androidx.datastore"
      curations:
        authors:
          - "The Android Open Source Project"
        concluded_license: "Apache-2.0"

    - id: "Maven:androidx.documentfile"
      curations:
        authors:
          - "The Android Open Source Project"
        concluded_license: "Apache-2.0"

    - id: "Maven:androidx.drawerlayout"
      curations:
        authors:
          - "The Android Open Source Project"
        concluded_license: "Apache-2.0"

    - id: "Maven:androidx.dynamicanimation"
      curations:
        authors:
          - "The Android Open Source Project"
        concluded_license: "Apache-2.0"

    - id: "Maven:androidx.exifinterface"
      curations:
        authors:
          - "The Android Open Source Project"
        concluded_license: "Apache-2.0"

    - id: "Maven:androidx.fragment"
      curations:
        authors:
          - "The Android Open Source Project"
        concluded_license: "Apache-2.0"

    - id: "Maven:androidx.interpolator"
      curations:
        authors:
          - "The Android Open Source Project"
        concluded_license: "Apache-2.0"

    - id: "Maven:androidx.legacy"
      curations:
        authors:
          - "The Android Open Source Project"
        concluded_license: "Apache-2.0"

    - id: "Maven:androidx.lifecycle"
      curations:
        authors:
          - "The Android Open Source Project"
        concluded_license: "Apache-2.0"

    - id: "Maven:androidx.loader"
      curations:
        authors:
          - "The Android Open Source Project"
        concluded_license: "Apache-2.0"

    - id: "Maven:androidx.localbroadcastmanager"
      curations:
        authors:
          - "The Android Open Source Project"
        concluded_license: "Apache-2.0"

    - id: "Maven:androidx.navigation"
      curations:
        authors:
          - "The Android Open Source Project"
        concluded_license: "Apache-2.0"

    - id: "Maven:androidx.print"
      curations:
        authors:
          - "The Android Open Source Project"
        concluded_license: "Apache-2.0"

    - id: "Maven:androidx.recyclerview"
      curations:
        authors:
          - "The Android Open Source Project"
        concluded_license: "Apache-2.0"

    - id: "Maven:androidx.resourceinspection"
      curations:
        authors:
          - "The Android Open Source Project"
        concluded_license: "Apache-2.0"

    - id: "Maven:androidx.savedstate"
      curations:
        authors:
          - "The Android Open Source Project"
        concluded_license: "Apache-2.0"

    - id: "Maven:androidx.security"
      curations:
        authors:
          - "The Android Open Source Project"
        concluded_license: "Apache-2.0"

    - id: "Maven:androidx.startup"
      curations:
        authors:
          - "The Android Open Source Project"
        concluded_license: "Apache-2.0"

    - id: "Maven:androidx.tracing"
      curations:
        authors:
          - "The Android Open Source Project"
        concluded_license: "Apache-2.0"

    - id: "Maven:androidx.transition"
      curations:
        authors:
          - "The Android Open Source Project"
        concluded_license: "Apache-2.0"

    - id: "Maven:androidx.vectordrawable"
      curations:
        authors:
          - "The Android Open Source Project"
        concluded_license: "Apache-2.0"

    - id: "Maven:androidx.versionedparcelable"
      curations:
        authors:
          - "The Android Open Source Project"
        concluded_license: "Apache-2.0"

    - id: "Maven:androidx.viewpager"
      curations:
        authors:
          - "The Android Open Source Project"
        concluded_license: "Apache-2.0"

    - id: "Maven:androidx.viewpager2"
      curations:
        authors:
          - "The Android Open Source Project"
        concluded_license: "Apache-2.0"

    - id: "Maven:org.jetbrains"
      curations:
        authors:
          - "The Android Open Source Project"
        concluded_license: "Apache-2.0"

    - id: "Maven:org.jetbrains.androidx.lifecycle"
      curations:
        authors:
          - "The Android Open Source Project"
        concluded_license: "Apache-2.0"

    - id: "Maven:org.jetbrains.androidx.savedstate"
      curations:
        authors:
          - "The Android Open Source Project"
        concluded_license: "Apache-2.0"

    - id: "Maven:org.jetbrains.compose.animation"
      curations:
        authors:
          - "The Android Open Source Project"
        concluded_license: "Apache-2.0"

    - id: "Maven:org.jetbrains.compose.annotation-internal"
      curations:
        authors:
          - "The Android Open Source Project"
        concluded_license: "Apache-2.0"

    - id: "Maven:org.jetbrains.compose.foundation"
      curations:
        authors:
          - "The Android Open Source Project"
        concluded_license: "Apache-2.0"

    - id: "Maven:org.jetbrains.compose.runtime"
      curations:
        authors:
          - "The Android Open Source Project"
        concluded_license: "Apache-2.0"

    - id: "Maven:org.jetbrains.compose.ui"
      curations:
        authors:
          - "The Android Open Source Project"
        concluded_license: "Apache-2.0"

    - id: "Maven:org.jetbrains.kotlin"
      curations:
        authors:
          - "The Android Open Source Project"
        concluded_license: "Apache-2.0"

    - id: "Maven:org.jetbrains.kotlinx"
      curations:
        authors:
          - "The Android Open Source Project"
        concluded_license: "Apache-2.0"

```
