### ISSUE TITLE
Allow curations with multiple paths

### ISSUE THREAD

**Issue by tsteenbe** [oss-review-toolkit/ort#5151]
The [annotations-2.0.0.jar file](https://repo1.maven.org/maven2/com/google/code/findbugs/annotations/2.0.0/annotations-2.0.0.jar) of Maven:com.google.code.findbugs:annotations contains other packages besides the source code found in the findbugs/src/java5/edu/umd/cs/findbugs/annotations within https://github.com/findbugsproject/findbugs.git. 

```
.
├── META-INF
│   └── MANIFEST.MF
├── edu
│   └── umd
├── javax
│   └── annotation
└── net
    └── jcip
```

Propose we allow setting multiple VCS paths like

```
- id: "Maven:com.google.code.findbugs:annotations"
  curations:
    comment: "Repository moved to GitHub."
    vcs:
      - url: "https://github.com/findbugsproject/findbugs.git"
         path: "findbugs/src/java5/edu/umd/cs/findbugs/annotations"
      - url: "https://github.com/javaee/javax.annotation"
         revision:  "abc12345"
```

**Comment by tsteenbe** [comment]
Noticed that for included net.jcip.annotation no source code repository is available but there is a [sources.jar](https://jcip.net/jcip-annotations-src.jar) see the page at https://jcip.net/. It may be better if we introduce a new element such as `sources` instead of changing VCS where `sources` could include multiple `source_artifact` or `vcs` elements e.g.:

```
- id: "Maven:com.google.code.findbugs:annotations"
  curations:
    comment: "Jar consist out of multiple packages and no sources jar available."
    sources:
      source_artifacts:
        - url: "https://jcip.net/jcip-annotations-src.jar"
          hash: "c685e640967c817cc66d9df598772e68721161f8 "
          hash_algorithm: "SHA1"
      vcs:
        - url: "https://github.com/findbugsproject/findbugs.git"
          path: "findbugs/src/java5/edu/umd/cs/findbugs/annotations"
        - url: "https://github.com/javaee/javax.annotation"
          revision:  "abc12345"
```

**Comment by tsteenbe** [comment]
Thought about it some more and maybe supporting a `contains` will be a better solution e.g.

```
- id: "Maven:com.google.code.findbugs:annotations:2.0.0"
  curations:
    comment: "Jar includes multiple packages not found in project's code repository. No sources jar available."
    vcs:
      url: "https://github.com/findbugsproject/findbugs.git"
      path: "findbugs/src/java5/edu/umd/cs/findbugs/annotations"
    contains:
      - "Maven:net.jcip:jcip-annotations:1.0"
      - "Maven:javax:annotation:unknown-version"
```
