### ISSUE TITLE
Pub: Support Git dependency definitions

### ISSUE THREAD

**Issue by MarcelBochtler** [oss-review-toolkit/ort#5196]
If a `pubspec.yaml` contains a [git dependency definition](https://docs.flutter.dev/development/packages-and-plugins/using-packages#dependencies-on-unpublished-packages):
```
dependencies:
  carousel_pro:
    git:
      url: https://github.com/jlouage/flutter-carousel-pro.git
      ref: master
```

The analyzer fails with the error:
```
issues:
  'Pub::pubspec.yaml:':
  - timestamp: "2022-03-28T11:53:08.317041Z"
    source: "Pub"
    message: "Resolving Pub dependencies for 'pubspec.yaml' failed with: IOException:\
      \ Could not find package info for carousel_pro"
    severity: "ERROR"
```

This breaks the analyzer run and no valid dependency tree is created.
