### ISSUE TITLE
python-inspector specify platform support

### ISSUE THREAD

**Issue by pepper-jk** [oss-review-toolkit/ort#5740]
## Context:

We have some windows python tools, which are scanned with ORT for licensing purposes. Even though the tool is created for windows and scanned on linux, ORT collects the macOS artifacts of the dependencies:

![2022-09-05 15 20 50-ORT Scan Report — Mozilla Firefox](https://user-images.githubusercontent.com/19859589/188470234-258e81a6-2aff-44e6-8533-f90bcb5e46b6.png)

## Feature Request:

Allow us to specify python version and platform (`macos`, `linux`, `windows`) manually, so that we can avoid potential licensing errors.

## Current Workaround:

`python-inspector` already allows users to specify the platform:

```
  -p, --python-version PYVER      Python version to use for dependency
                                  resolution.  [default: 38]
  -o, --operating-system OS       OS to use for dependency resolution.
                                  [default: linux]
```

I tried to hard code `windows` into my local ort image by editiing the `run` function in the `PythonInspector` object:

```kotlin
    fun run(
        workingDir: File,
        outputFile: String,
        definitionFile: File,
        pythonVersion: String = "38",
    ): ProcessCapture {
        val commandLineOptions = buildList {
            add("--python-version")
            add(pythonVersion)

            add("--operating-system")
            add("windows")

            add("--json-pdt")
            add(outputFile)

            if (definitionFile.name == "setup.py") {
                add("--setup-py")
            } else {
                add("--requirement")
            }

            add(definitionFile.absolutePath)
        }
```

orignal code:

https://github.com/oss-review-toolkit/ort/blob/e8a951080b15d38375b333d5559b651e5ef6c713/analyzer/src/main/kotlin/managers/Pip.kt#L146-L166

Sadly this did not work for me, although I do not understand why.

Could you point me into the right direction? I really need a workaround for this, until ort has a proper CLI param for it.

## Additional Information:

This is being worked on already. See also:
https://github.com/oss-review-toolkit/ort/issues/3671
https://github.com/oss-review-toolkit/ort/issues/3671#issuecomment-1203248523
https://github.com/oss-review-toolkit/ort/issues/4637

I noticed that the artifact files for windows, macOS and linux have quite different name formatting for the pillow package:
https://pypi.org/project/Pillow/9.2.0/#files

Maybe this contributes to the issue.

**Comment by sschuberth** [comment]
> We have some windows python tools, which are scanned with ORT for licensing purposes. Even though the tool is created for windows and scanned on linux, ORT collects the macOS artifacts of the dependencies:

This is also semi-related to the general issue described at https://github.com/oss-review-toolkit/ort/issues/4013.

**Comment by pepper-jk** [comment]
> This is also semi-related to the general issue described at #4013.

In the merge attached to this issue I found this:

```
  binary_artifact:
    url: "https://files.pythonhosted.org/packages/c4/af/93fb95dc8bc90a5580084f3dc4be049d243c6f687ff2e253ed3a6df30db4/itsdangerous-2.0.0-py3-none-any.whl"
```
https://github.com/oss-review-toolkit/ort/pull/4011/files#diff-fdaab681c9cf677a77196de07d376e9e12656aa18af3d7d293a0d4e24f6e0088R181-R182

Can I specify this within a package configuration?

If so, this would be a possible workaround until specifying the platform is possible. It also would not require to build a modified ort-image.

**Comment by mnonnenmacher** [comment]
@pepper-jk We are currently waiting for https://github.com/nexB/python-inspector to provide metadata for packages. Once this is implemented, we can get independent of the local operating system and the installed Python version, and will make these available as package manager options which can be set in the `.ort.yml` and on the command line. This will hopefully happen soon, until then we have to rely on a combination of running local commands like `pip install` and `pip show` and running `python-inspector` which will not always created consistent results.

Nevertheless, I'm surprised that you get the binary artifact for Mac on a Linux machine, because IIRC we get that data from `pip show` which reads data from locally installed packages. If you can provide a small example project that reproduces this issue we could check if this can be fixed independently of a `python-inspector` upgrade.

**Comment by pepper-jk** [comment]
> Nevertheless, I'm surprised that you get the binary artifact for Mac on a Linux machine, because IIRC we get that data from `pip show` which reads data from locally installed packages. If you can provide a small example project that reproduces this issue we could check if this can be fixed independently of a `python-inspector` upgrade.

I can confirm that I get the same macOS artifact for pillow with this [example repo](https://github.com/pepper-jk/ort_pypi_resolution_test), that only contains our requirements.txt.

I used our production pipeline for the scan, though. It is possible that our gitlab pipeline introduces something that triggers it or the ort-config we use. I doubt the latter though, since our base config does not contain any package configuration.

@jens-erdmann maybe you can provide some information on our gitlab pipeline? I only know that they are linux kubernetes runners.

Maybe you could confirm if this issue also applies for a the plain ort docker image, @mnonnenmacher ?

**Comment by pepper-jk** [comment]
Hi @mnonnenmacher,
today we have reproduced the problem on an Ubuntu VM outside our pipeline. Again using the [example repo](https://github.com/pepper-jk/ort_pypi_resolution_test) linked above.

We ran the docker image as follows:
```
$ docker run --rm -it -v $SSH_AUTH_SOCK:/ssh-agent -e SSH_AUTH_SOCK=/ssh-agent -v $PWD:/project -v ~/code/ort-config:/config --entrypoint=/bin/bash ort-image:5c6fc850b0b1b0a2734e8de14c9d2b1a7b85cd73
$ cp -r /project ./
$ ort --info analyze -i /home/ort/project -o /home/ort/project/ort/analyzer/
```

And got the following metadata for `pillow:9.2.0` in the `analyzer-results.yml`:
```
    - metadata:
        id: "PyPI::pillow:9.2.0"
        purl: "pkg:pypi/pillow@9.2.0"
        authors:
        - "Alex Clark (PIL Fork Author)"
        declared_licenses:
        - "HPND"
        - "Historical Permission Notice and Disclaimer (HPND)"
        declared_licenses_processed:
          spdx_expression: "HPND"
          mapped:
            Historical Permission Notice and Disclaimer (HPND): "HPND"
        description: "Python Imaging Library (Fork)"
        homepage_url: "https://python-pillow.org"
        binary_artifact:
          url: "https://files.pythonhosted.org/packages/d8/60/b13c00d403f34110e96c1b5c0afa73ce461efe3fe960c3a7e3e7fe190d82/Pillow-9.2.0-cp310-cp310-macosx_10_10_x86_64.whl"
          hash:
            value: "deb973d5f3b7dd5827667a170526d8ce"
            algorithm: "MD5"
        source_artifact:
          url: "https://files.pythonhosted.org/packages/8c/92/2975b464d9926dc667020ed1abfa6276e68c3571dcb77e43347e15ee9eed/Pillow-9.2.0.tar.gz"
          hash:
            value: "218bdb951f3e59e8b782e329ece3416d"
            algorithm: "MD5"
        vcs:
          type: ""
          url: ""
          revision: ""
          path: ""
        vcs_processed:
          type: "Git"
          url: "https://github.com/python-pillow/Pillow.git"
          revision: ""
          path: ""
      curations: []
```

We got the same for `markupsafe:2.1.1`.

<details>
<summary>The complete yml</summary>
```
---
repository:
  vcs:
    type: "Git"
    url: "https://github.com/pepper-jk/ort_pypi_resolution_test"
    revision: "3f0cafa8f4054bba83c5aedd7740b8a802bc794c"
    path: ""
  vcs_processed:
    type: "Git"
    url: "https://github.com/pepper-jk/ort_pypi_resolution_test.git"
    revision: "3f0cafa8f4054bba83c5aedd7740b8a802bc794c"
    path: ""
  config: {}
analyzer:
  start_time: "2022-10-11T12:51:22.242810Z"
  end_time: "2022-10-11T12:51:45.725180Z"
  environment:
    ort_version: "DOCKER-SNAPSHOT-5c6fc850b0b1b0a2734e8de14c9d2b1a7b85cd73"
    java_version: "11.0.16.1"
    os: "Linux"
    processors: 4
    max_memory: 4196401152
    variables:
      TERM: "xterm"
      http_proxy: "http://proxy.com:3128"
      https_proxy: "http://proxy.com:3128"
      JAVA_HOME: "/opt/java/openjdk"
      ANDROID_HOME: "/opt/android-sdk"
    tool_versions:
      PIP: "22.2.2"
  config:
    allow_dynamic_versions: false
  result:
    projects:
    - id: "PIP::requirements.txt:3f0cafa8f4054bba83c5aedd7740b8a802bc794c"
      definition_file_path: "requirements.txt"
      declared_licenses: []
      declared_licenses_processed: {}
      vcs:
        type: ""
        url: ""
        revision: ""
        path: ""
      vcs_processed:
        type: "Git"
        url: "https://github.com/pepper-jk/ort_pypi_resolution_test.git"
        revision: "3f0cafa8f4054bba83c5aedd7740b8a802bc794c"
        path: ""
      homepage_url: ""
      scope_names:
      - "install"
    packages:
    - metadata:
        id: "PyPI::jinja2:3.1.2"
        purl: "pkg:pypi/jinja2@3.1.2"
        authors:
        - "Armin Ronacher"
        declared_licenses:
        - "BSD License"
        - "BSD-3-Clause"
        declared_licenses_processed:
          spdx_expression: "BSD-3-Clause"
          mapped:
            BSD License: "BSD-3-Clause"
        description: "A very fast and expressive template engine."
        homepage_url: "https://palletsprojects.com/p/jinja/"
        binary_artifact:
          url: "https://files.pythonhosted.org/packages/bc/c3/f068337a370801f372f2f8f6bad74a5c140f6fda3d9de154052708dd3c65/Jinja2-3.1.2-py3-none-any.whl"
          hash:
            value: "00ccdb509d3592cc2163b286177d75c8"
            algorithm: "MD5"
        source_artifact:
          url: "https://files.pythonhosted.org/packages/7a/ff/75c28576a1d900e87eb6335b063fab47a8ef3c8b4d88524c4bf78f670cce/Jinja2-3.1.2.tar.gz"
          hash:
            value: "d31148abd89c1df1cdb077a55db27d02"
            algorithm: "MD5"
        vcs:
          type: ""
          url: ""
          revision: ""
          path: ""
        vcs_processed:
          type: "Git"
          url: "https://github.com/pallets/jinja.git"
          revision: ""
          path: ""
      curations: []
    - metadata:
        id: "PyPI::markupsafe:2.1.1"
        purl: "pkg:pypi/markupsafe@2.1.1"
        authors:
        - "Armin Ronacher"
        declared_licenses:
        - "BSD License"
        - "BSD-3-Clause"
        declared_licenses_processed:
          spdx_expression: "BSD-3-Clause"
          mapped:
            BSD License: "BSD-3-Clause"
        description: "Safely add untrusted strings to HTML/XML markup."
        homepage_url: "https://palletsprojects.com/p/markupsafe/"
        binary_artifact:
          url: "https://files.pythonhosted.org/packages/d9/60/94e9de017674f88a514804e2924bdede9a642aba179d2045214719d6ec76/MarkupSafe-2.1.1-cp310-cp310-macosx_10_9_universal2.whl"
          hash:
            value: "edd92cc0efdc919430f86fac719864d7"
            algorithm: "MD5"
        source_artifact:
          url: "https://files.pythonhosted.org/packages/1d/97/2288fe498044284f39ab8950703e88abbac2abbdf65524d576157af70556/MarkupSafe-2.1.1.tar.gz"
          hash:
            value: "9809f9fdd98bc835b0c21aa8f79cbf30"
            algorithm: "MD5"
        vcs:
          type: ""
          url: ""
          revision: ""
          path: ""
        vcs_processed:
          type: "Git"
          url: "https://github.com/pallets/markupsafe.git"
          revision: ""
          path: ""
      curations: []
    - metadata:
        id: "PyPI::pillow:9.2.0"
        purl: "pkg:pypi/pillow@9.2.0"
        authors:
        - "Alex Clark (PIL Fork Author)"
        declared_licenses:
        - "HPND"
        - "Historical Permission Notice and Disclaimer (HPND)"
        declared_licenses_processed:
          spdx_expression: "HPND"
          mapped:
            Historical Permission Notice and Disclaimer (HPND): "HPND"
        description: "Python Imaging Library (Fork)"
        homepage_url: "https://python-pillow.org"
        binary_artifact:
          url: "https://files.pythonhosted.org/packages/d8/60/b13c00d403f34110e96c1b5c0afa73ce461efe3fe960c3a7e3e7fe190d82/Pillow-9.2.0-cp310-cp310-macosx_10_10_x86_64.whl"
          hash:
            value: "deb973d5f3b7dd5827667a170526d8ce"
            algorithm: "MD5"
        source_artifact:
          url: "https://files.pythonhosted.org/packages/8c/92/2975b464d9926dc667020ed1abfa6276e68c3571dcb77e43347e15ee9eed/Pillow-9.2.0.tar.gz"
          hash:
            value: "218bdb951f3e59e8b782e329ece3416d"
            algorithm: "MD5"
        vcs:
          type: ""
          url: ""
          revision: ""
          path: ""
        vcs_processed:
          type: "Git"
          url: "https://github.com/python-pillow/Pillow.git"
          revision: ""
          path: ""
      curations: []
    - metadata:
        id: "PyPI::pyglet:1.5.26"
        purl: "pkg:pypi/pyglet@1.5.26"
        authors:
        - "Alex Holkner"
        declared_licenses:
        - "BSD"
        - "BSD License"
        declared_licenses_processed:
          spdx_expression: "BSD-3-Clause"
          mapped:
            BSD: "BSD-3-Clause"
            BSD License: "BSD-3-Clause"
        description: "Cross-platform windowing and multimedia library"
        homepage_url: "http://pyglet.readthedocs.org/en/latest/"
        binary_artifact:
          url: "https://files.pythonhosted.org/packages/68/52/10c1826df26e59d989b115bd5ee19535cae8cbfff642f1495fc62f24b01f/pyglet-1.5.26-py3-none-any.whl"
          hash:
            value: "f1da62163a65ee518469c210058dd3c9"
            algorithm: "MD5"
        source_artifact:
          url: "https://files.pythonhosted.org/packages/85/5d/2d52c9441344802f081d1cda30839e5534845d52048629188bafba475444/pyglet-1.5.26.zip"
          hash:
            value: "61da58d945346cc9adbd3acd1e4fd8dd"
            algorithm: "MD5"
        vcs:
          type: ""
          url: ""
          revision: ""
          path: ""
        vcs_processed:
          type: "Git"
          url: "https://github.com/pyglet/pyglet.git"
          revision: ""
          path: ""
      curations: []
    - metadata:
        id: "PyPI::pywavefront:1.3.3"
        purl: "pkg:pypi/pywavefront@1.3.3"
        authors:
        - "Kurt Yoder"
        declared_licenses:
        - "BSD"
        - "BSD License"
        declared_licenses_processed:
          spdx_expression: "BSD-3-Clause"
          mapped:
            BSD: "BSD-3-Clause"
            BSD License: "BSD-3-Clause"
        description: "Python library for importing Wavefront .obj files"
        homepage_url: "https://github.com/pywavefront/PyWavefront"
        binary_artifact:
          url: "https://files.pythonhosted.org/packages/fe/f2/db25754f3d7f948e1cb7191a393284e29bc2497dae9d8456cbf25ddac671/PyWavefront-1.3.3-py3-none-any.whl"
          hash:
            value: "fb87b53d8e143a7d0f057c1ca4575f4f"
            algorithm: "MD5"
        source_artifact:
          url: ""
          hash:
            value: ""
            algorithm: ""
        vcs:
          type: ""
          url: ""
          revision: ""
          path: ""
        vcs_processed:
          type: "Git"
          url: "https://github.com/pywavefront/PyWavefront.git"
          revision: ""
          path: ""
      curations: []
    dependency_graphs:
      PIP:
        packages:
        - "PyPI::jinja2:3.1.2"
        - "PyPI::markupsafe:2.1.1"
        - "PyPI::pillow:9.2.0"
        - "PyPI::pyglet:1.5.26"
        - "PyPI::pywavefront:1.3.3"
        scopes:
          :requirements.txt:3f0cafa8f4054bba83c5aedd7740b8a802bc794c:install:
          - root: 0
          - root: 2
          - root: 3
          - root: 4
        nodes:
        - pkg: 1
        - {}
        - pkg: 2
        - pkg: 3
        - pkg: 4
        edges:
        - from: 1
          to: 0
    has_issues: false
scanner: null
advisor: null
evaluator: null
```
</details>

**Comment by sschuberth** [comment]
> However, we used a more recent image [5c6fc85](https://github.com/oss-review-toolkit/ort/commit/5c6fc850b0b1b0a2734e8de14c9d2b1a7b85cd73).

@pepper-jk this should have been improved just today with https://github.com/oss-review-toolkit/ort/pull/5910. Please give this another try.

**Comment by pepper-jk** [comment]
Thanks, we will. The image build of the current master is running.

I will update you tomorrow.

**Comment by pepper-jk** [comment]
I can now confirm that a scan with ORT on ec7d0b1 does not have the macOS binary artifact problem anymore.

I assume #5910 fixed this bug.

We now get the following metadata for `pillow:9.2.0` in the `analyzer-results.yml`:

```
    - metadata:
        id: "PyPI::pillow:9.2.0"
        purl: "pkg:pypi/pillow@9.2.0"
        authors:
        - "Alex Clark (PIL Fork Author) <aclark@python-pillow.org>"
        declared_licenses:
        - "HPND"
        declared_licenses_processed:
          spdx_expression: "HPND"
        description: "<p align=\"center\">"
        homepage_url: "https://python-pillow.org"
        binary_artifact:
          url: "https://files.pythonhosted.org/packages/c4/ac/a50a4a11fe2120d3047b567f765afb54d6c57bad704e8c9759153b6359e4/Pillow-9.2.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl"
          hash:
            value: "1cc1d2451e8a3b4bfdb9caf745b58e6c7a77d2e469159b0d527a4554d73694d1"
            algorithm: "SHA-256"
        source_artifact:
          url: "https://files.pythonhosted.org/packages/8c/92/2975b464d9926dc667020ed1abfa6276e68c3571dcb77e43347e15ee9eed/Pillow-9.2.0.tar.gz"
          hash:
            value: "75e636fd3e0fb872693f23ccb8a5ff2cd578801251f3a4f6854c6a5d437d3c04"
            algorithm: "SHA-256"
        vcs:
          type: ""
          url: ""
          revision: ""
          path: ""
        vcs_processed:
          type: "Git"
          url: "https://github.com/python-pillow/Pillow.git"
          revision: ""
          path: ""
      curations: []
```

Same goes for `markupsafe:2.1.1`.

**Comment by pepper-jk** [comment]
I will keep the issue open though, until passing a platform manually is possible in ORT.

**Comment by mnonnenmacher** [comment]
@pepper-jk This was already implemented in #5910. You can configure the python version or operating system either in the global configuration or in your .ort.yml like this:
```yaml
analyzer:
  packageManagers: # package_managers in .ort.yml IIRC
    Pip:
      options:
        operatingSystem: linux
        pythonVersion: 3.8
```
