### ISSUE TITLE
Wrong matching with [AntPathMatcher] for path exclude

### ISSUE THREAD

**Issue by nnobelis** [oss-review-toolkit/ort#5901]
We have a project with the following path exclude
```
paths:
    - pattern: "{gradlew,gradlew.bat}"
      reason: "BUILD_TOOL_OF"
      comment: "Gradle build files"
```
However it seems this pattern excludes the `build.gradle` in the project.

After debugging, I came to evaluate this bit of code in ORT Reporter:
```
AntPathMatcher().apply { setCaseSensitive(true) }.match("{gradlew,gradlew.bat}", "build.gradle")
```
and to my surprise it evaluates to  `true`.

Has anyone an idea what happens here ?
It does not seem to conform to what's in Spring Javadoc [1].

As a sidenote, should ORT not use [2] instead for glob matching ?

[1]: https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/util/AntPathMatcher.html
[2]: https://docs.oracle.com/javase/7/docs/api/java/nio/file/FileSystem.html#getPathMatcher(java.lang.String)
