### ISSUE TITLE
how to use notifier with ORT 

### ISSUE THREAD

**Issue by roshvin** [oss-review-toolkit/ort#6048]
https://github.com/oss-review-toolkit/ort/blob/main/model/src/main/resources/reference.yml
as per this doc we are setting up notifier  , how can we give target end user mail id here to send mail notification. 

```
 notifier:
    mail:
      hostName: 'localhost'
      username: user
      password: password
      port: 465
      useSsl: true
      fromAddress: 'no-reply@oss-review-toolkit.org'
```
