### ISSUE TITLE
Git returns wrong nested repositories for uninitialized submodule

### ISSUE THREAD

**Issue by mnonnenmacher** [oss-review-toolkit/ort#6146]
When running the analyzer on a project with uninitialized Git submodules, the nested repository information is wrong. For each uninitialized submodule it contains the original repository. The expected behavior would be to either fail or not return any entry for the uninitialized submodule.

This can be reproduced by running the analyzer on the https://github.com/oss-review-toolkit/ort-test-data-git-submodules repository without initializing the submodules. The analyzer result contains the following repositories:

```yaml
repository:
  vcs:
    type: "Git"
    url: "git@github.com:oss-review-toolkit/ort-test-data-git-submodules.git"
    revision: "fcea94bab5835172e826afddb9f6427274c983b9"
    path: ""
  vcs_processed:
    type: "Git"
    url: "ssh://git@github.com/oss-review-toolkit/ort-test-data-git-submodules.git"
    revision: "fcea94bab5835172e826afddb9f6427274c983b9"
    path: ""
  nested_repositories:
    commons-text:
      type: "Git"
      url: "git@github.com:oss-review-toolkit/ort-test-data-git-submodules.git"
      revision: "fcea94bab5835172e826afddb9f6427274c983b9"
      path: "commons-text"
    test-data-npm:
      type: "Git"
      url: "git@github.com:oss-review-toolkit/ort-test-data-git-submodules.git"
      revision: "fcea94bab5835172e826afddb9f6427274c983b9"
      path: "test-data-npm"
```
