### ISSUE TITLE
curations: version range not working for 4 digit versions

### ISSUE THREAD

**Issue by mawl** [oss-review-toolkit/ort#6153]
Hey,

Concerning curations, it seems that ivy-style version ranges doesn't work for four digit versions like 1.1.1.3.

ivy-style version matcher introduction: https://docs.gradle.org/current/userguide/single_versions.html

### single version 1.1.1.3
NuGet::Xamarin.Android.Arch.Core.Common:1.1.1.3
```
    - metadata:
        id: "NuGet::Xamarin.Android.Arch.Core.Common:1.1.1.3"
      curations:
      - base: {}
        curation:
          comment: "https://go.microsoft.com/fwlink/?linkid=865381 contains MIT License"
          declared_license_mapping:
            https://go.microsoft.com/fwlink/?linkid=865381: "MIT"
```

### prefix matcher 1.1.1.+
NuGet::Xamarin.Android.Arch.Core.Common:1.1.1.+
```
    - metadata:
        id: "NuGet::Xamarin.Android.Arch.Core.Common:1.1.1.3"
      curations:
      - base: {}
        curation:
          comment: "https://go.microsoft.com/fwlink/?linkid=865381 contains MIT License"
          declared_license_mapping:
            https://go.microsoft.com/fwlink/?linkid=865381: "MIT"
```

### prefix matcher 1.+
NuGet::Xamarin.Android.Arch.Core.Common:1.+
```
    - metadata:
        id: "NuGet::Xamarin.Android.Arch.Core.Common:1.1.1.3"
      curations:
      - base: {}
        curation:
          comment: "https://go.microsoft.com/fwlink/?linkid=865381 contains MIT License"
          declared_license_mapping:
            https://go.microsoft.com/fwlink/?linkid=865381: "MIT"
```

### version range [1.1.1,)
NuGet::Xamarin.Android.Arch.Core.Common:\[1.1.1,)
```
    - metadata:
        id: "NuGet::Xamarin.Android.Arch.Core.Common:1.1.1.3"
      curations: []
```

### version range [1.1.1.1,)
NuGet::Xamarin.Android.Arch.Core.Common:\[1.1.1.1,)
```
    - metadata:
        id: "NuGet::Xamarin.Android.Arch.Core.Common:1.1.1.3"
      curations: []
```

Can you please check that?
