### ISSUE TITLE
Nested provenance cannot be resolved because SVN path is not found

### ISSUE THREAD

**Issue by bennati** [oss-review-toolkit/ort#6160]
When scanning https://github.com/apache/maven-doxia/tree/doxia-1.1.2/doxia-core
The scanner returns the following error:
```
Could not resolve nested provenance for package 'Maven:xml-apis:xml-apis:1.3.03': SVNException: svn: E160005: Target path '/xerces/xml-commons' does not exist svn: E175002: REPORT of '/repos/asf/!svn/vcc/default': 500 Internal Server Error (https://svn.apache.org)
```
Despite the path existing https://svn.apache.org/repos/asf/xerces/xml-commons/tags/xml-commons-external-1_3_03/

This is our curation, that has worked until now:
```
- id: "Maven:xml-apis:xml-apis:1.3.03"
  curations:
    ...
    vcs:
      type: "Subversion"
      url: "https://svn.apache.org/repos/asf/xerces/xml-commons"
      revision: "tags/xml-commons-external-1_3_03"
```
