### ISSUE TITLE
Dependency Graph Information Missing in CycloneDX SBOMs

### ISSUE THREAD

**Issue by twright-0x1** [oss-review-toolkit/ort#6396]
This has a tangential relation to the earlier issue #3906.

When I use ort to generate an sbom, if the sbom type is SPDX, I see dependency graph information (at the end of the SBOM file).  Whereas, if I select CycloneDX as the type, it appears that dependency graph information is missing.

My test case is a clone of the WebGoat project.  I'm using a Docker install of ort... If I generate an Analyzer file with:

`docker run --rm -v /MyStuff/:/project ort --info analyze -i /project/WebGoat --output-dir /project`

and then an SPDX SBOM with:

`docker run --rm -v /MyStuff/:/project ort --info report -i /project/analyzer-result.yml -f SpdxDocument -o /project`

I see the expected dependency graph information at the end of the file.  E.g., here's a snippet:

```
relationships:
- spdxElementId: "SPDXRef-Package-Maven-cglib-cglib-nodep-2.2"
  relationshipType: "GENERATED_FROM"
  relatedSpdxElement: "SPDXRef-Package-Maven-cglib-cglib-nodep-2.2-source-artifact"
- spdxElementId: "SPDXRef-Package-Maven-ch.qos.logback-logback-classic-1.2.11"
  relationshipType: "DEPENDS_ON"
  relatedSpdxElement: "SPDXRef-Package-Maven-ch.qos.logback-logback-core-1.2.11"
```

Whereas, if I generate a CycloneDX SBOM with:

`docker run --rm -v /MyStuff/:/project ort --info report -i /project/analyzer-result.yml -f CycloneDx -o /project`

I don't find any dependency data.
