### ISSUE TITLE
"sub-packages" inheriting license and attributes of parent packages

### ISSUE THREAD

**Issue by dgutson** [oss-review-toolkit/ort#6753]
Consider this from the analyzer-result.yml:
```yaml
    - id: "NPM:@glimmer:compiler:0.22.3"
      purl: "pkg:npm/%40glimmer/compiler@0.22.3"
      declared_licenses: []
      declared_licenses_processed: {}
      description: ""
      homepage_url: ""
      binary_artifact:
        url: ""
        hash:
          value: ""
          algorithm: ""
      source_artifact:
        url: "https://registry.npmjs.org/@glimmer/compiler/-/compiler-0.22.3.tgz"
        hash:
          value: "3aef9448460af1d320a82423323498a6ff38a0c6"
          algorithm: "SHA-1"
      vcs:
        type: "Git"
        url: "https://github.com/glimmerjs/glimmer-vm/tree/master/packages/@glimmer/compiler"
        revision: ""
        path: ""
      vcs_processed:
        type: "Git"
        url: "https://github.com/glimmerjs/glimmer-vm.git"
        revision: "master"
        path: "packages/@glimmer/compiler"
```

It is a plugin that belongs to the "parent" project here: https://github.com/glimmerjs/glimmer-vm
which contains all the attributes (license, etc.).
Of course ORT is unable to extract proper information. How could we improve this? Maybe some sort of "backtracking" (or upstream traversing) the URL path until finding the information?
