### ISSUE TITLE
Scanner: Config parsing error when trying to use an http storage backend

### ISSUE THREAD

**Issue by AndreasHennig** [oss-review-toolkit/ort#6758]
During the scan process I would like to use an **http storage backend** (https://github.com/oss-review-toolkit/ort#http-storage) as a caching mechanism to speed up the scan process for consecutive scans.

Based on what I found in the reference config file (https://github.com/oss-review-toolkit/ort/blob/main/model/src/main/resources/reference.yml#L219) I adjusted my global **config.yml** the following:

```yaml
  scanner:
    # (...)

    storages:
      local:
        backend:
          localFileStorage:
            directory: ~/.ort/scanner/results
            compression: false

      http:
        backend:
          httpFileStorage:
            url: 'https://url-to-http-server.com'

    storageReaders: [local, http]
    storageWriters: [local, http]

    # (...)
```

However, when I  execute the scan command I immediately get a config parsing error:

**Input:**
```bash
./cli/build/install/ort/bin/ort --info scan --package-types PACKAGE -f JSON -i path/to/analyzer-result.json -o path/to/output/folder
```

**Output:**
```bash
[main] INFO  org.ossreviewtoolkit.model.config.OrtConfiguration - Using ORT configuration file '/Users/Hennig/.ort/config/config.yml'.
Exception in thread "main" java.lang.IllegalArgumentException: Failed to load ORT configuration: - Could not instantiate 'org.ossreviewtoolkit.model.config.OrtConfigurationWrapper' because:

    - 'ort': - Could not instantiate 'org.ossreviewtoolkit.model.config.OrtConfiguration' because:

        - 'scanner': - Could not instantiate 'org.ossreviewtoolkit.model.config.ScannerConfiguration' because:

            - 'storages': Collection element decode failure (/Users/Hennig/.ort/config/config.yml:145:6):

                Could not find appropriate subclass of class org.ossreviewtoolkit.model.config.ScanStorageConfiguration: Tried org.ossreviewtoolkit.model.config.ClearlyDefinedStorageConfiguration, org.ossreviewtoolkit.model.config.FileBasedStorageConfiguration, org.ossreviewtoolkit.model.config.PostgresStorageConfiguration, org.ossreviewtoolkit.model.config.Sw360StorageConfiguration (/Users/Hennig/.ort/config/config.yml:152:8)
```

Am I doing something wrong here?

---

As a side note: First looking at the appropriate section in the README.md (https://github.com/oss-review-toolkit/ort#http-storage) was a bit confusing. I expected some kind of storage named "http-server". But the one listed there is called `artifactoryStorage`:
```yaml
ort:
  scanner:
    storages:
      artifactoryStorage:
        backend:
          httpFileStorage:
            url: "https://artifactory.domain.com/artifactory/repository/scan-results"
            headers:
              X-JFrog-Art-Api: "api-token"
              
    storageReaders: ["artifactoryStorage"]
    storageWriters: ["artifactoryStorage"]
```

I am assuming `artifactoryStorage` to just be an arbitrary name for an `httpFileStorage`. As long as the the same name is used to set the storage in the `storageReaders` / `storageWriters` it should work. Is my assumption correct?
