### ISSUE TITLE
evaluator passes wrong detected license to `rules.kts` when license choice was made

### ISSUE THREAD

**Issue by fviernau** [oss-review-toolkit/ort#6812]
Given:

1. Detected license: `BSD-3-Clause OR GPL-2.0-only`.
2. License choice in `ort.yml`
```
license_choices:
  package_license_choices:
  - package_id: "NPM::node-forge:1.3.1"
    license_choices:
    - given: "BSD-3-Clause OR GPL-2.0-only"
      choice: "BSD-3-Clause"
```
3. The "effective license" shown in the WebApp indicates that the license choice eliminated `GPL-2.0-only`.

Reproduce:

1. Run evaluator with upstream `ort-config` policy rules

Outcome: GPL-2.0-only is flagged for `NPM::node-forge:1.3.1`.
