### ISSUE TITLE
Error while using resolutions.yml file

### ISSUE THREAD

**Issue by saaskesaakura345** [oss-review-toolkit/ort#6997]
Hello team,

I am facing an error while trying to use the resolution file to resolve the violations.
Seeking your support to understand the issue. Please find the details on the input provided.
Note:-  While trying only for the vulnerabilities, it worked.
But the rule_violations, is throwing below attached error.

resolutions.yml file used.
```
vulnerabilities:
- id: "GHSA-ww39-953v-wcq6"
  reason: "INVALID_MATCH_VULNERABILITY"
  comment: "A vulnerability resolution which resolves only vulnerabilities for testing."

rule_violations:
- message: "The dependency NPM::ismyself:1.0.2 is licensed under the 'network-copyleft' categorized license AGPL-3.0-or-later. This requires approval of the OSPO."
  reason: "CANT_FIX_EXCEPTION"
  comment: "overide this policy."
```
**Command used:**
```
run:  ort/bin/ort report -i ./evaluation-result.yml -f WebApp --resolutions-file ./resolutions.yml -o ./
```
**Error message received.**

![image](https://github.com/oss-review-toolkit/ort/assets/128026849/d490f26a-e658-4714-8164-2275665a6bf9)

**Comment by tsteenbe** [comment]
@saaskesaakura345  This type of error is what you normally get when your resolutions.yml is invalid YAML e.g. incorrect indentation or hidden zero-width charactor. I can't narrow down the issue without the original resolutions.yml file, recommend use you use your IDE YAML linter or https://www.yamllint.com/  to find the root cause of the issue.

**Comment by saaskesaakura345** [comment]
@tsteenbe Thank you for your prompt response. I am super excited and eagerly looking forward exploring ORT tool.

Please find the **resolutions.yml** file that i am exploring ORT with.
The ID and message was taken from "evaluation-result.yml file"
```
vulnerabilities:
- id: "GHSA-ww39-953v-wcq6"
  reason: "INVALID_MATCH_VULNERABILITY"
  comment: "A vulnerability resolution which resolves only vulnerabilities for testing."

rule_violations:
- message: ".*NPM::ismyself:1.0.2 .*"
  reason: "CANT_FIX_EXCEPTION"
  comment: "overide this policy."

```

Now I am able to get a success scan, but the resolutions provided above are not reflected in report.
I am passing this file to the reporter module as below.
```
run:  ort/bin/ort report -i ./evaluation-result.yml -f WebApp --resolutions-file ./resolutions.yml -o ./
```

**Comment by tsteenbe** [comment]
@saaskesaakura345  in .*NPM::ismyself:1.0.2 .*" there is a space after the 2 which might be the issue. FYI for these type of basic issues the quickest way to get support is actually via the [ORT Slack](https://join.slack.com/t/ort-talk/shared_invite/zt-1c7yi4sj6-mk7R1fAa6ZdW5MQ6DfAVRg) channel.

**Comment by fviernau** [comment]
You may try this:

```
resolutions:
  vulnerabilities:
  - id: "GHSA-ww39-953v-wcq6"
    reason: "INVALID_MATCH_VULNERABILITY"
    comment: "A vulnerability resolution which resolves only vulnerabilities for testing."
  rule_violations:
  - message: ".*NPM::ismyself:1.0.2 .*"
    reason: "CANT_FIX_EXCEPTION"
    comment: "overide this policy."
```
