### ISSUE TITLE
Does repository_license_choices has an effect on CycloneDXReporter sbom output?

### ISSUE THREAD

**Issue by mawl** [oss-review-toolkit/ort#7182]
Hey,

I wonder if repository_license_choices has an effect on sbom output generated by CycloneDXReporter.

https://github.com/oss-review-toolkit/ort/blob/9cbcf9fb23fda6984a530bce5c096492a09e3e07/plugins/reporters/cyclonedx/src/main/kotlin/CycloneDxReporter.kt#L271

Here's an example:
#### analyzer-result.yml
```yml
   - id: "NPM::pizzip:3.1.4"
      purl: "pkg:npm/pizzip@3.1.4"
      authors:
      - "Edgar Hipp"
      declared_licenses:
      - "(MIT OR GPL-3.0)"
      declared_licenses_processed:
        spdx_expression: "GPL-3.0-only OR MIT"
        mapped:
          (MIT OR GPL-3.0): "MIT OR GPL-3.0-only"
      description: "Create, read and edit .zip files synchronously with Javascript"
      homepage_url: "https://github.com/open-xml-templating/pizzip#readme"
...
```
#### evaluation-result.yml
```yml
 config:
...
    license_choices:
      repository_license_choices:
      - given: "GPL-3.0-only OR MIT"
        choice: "MIT"
      - given: "MIT OR GPL-3.0-only"
        choice: "MIT"
...
   - id: "NPM::pizzip:3.1.4"
      purl: "pkg:npm/pizzip@3.1.4"
      authors:
      - "Edgar Hipp"
      declared_licenses:
      - "(MIT OR GPL-3.0)"
      declared_licenses_processed:
        spdx_expression: "GPL-3.0-only OR MIT"
        mapped:
          (MIT OR GPL-3.0): "MIT OR GPL-3.0-only"
      description: "Create, read and edit .zip files synchronously with Javascript"
      homepage_url: "https://github.com/open-xml-templating/pizzip#readme"
```
####  ORT Scan Report > Tree
Effective SPDX is MIT, license choice works:
![image](https://github.com/oss-review-toolkit/ort/assets/5493374/51109bba-5e3c-4f47-a2e6-74a8e0150317)

#### bom.cyclonedx.json
Still both licenses in sbom - license choice has no effect.
```json
    {
      "group": "",
      "name": "pizzip",
      "version": "3.1.4",
      "description": "Create, read and edit .zip files synchronously with Javascript",
      "scope": "required",
      "hashes": [
        {
          "alg": "SHA-1",
          "content": "0c2578506ce5b487fa00bc2dd62eebeb291ee677"
        }
      ],
      "licenses": [
        {
          "license": {
            "id": "GPL-3.0-only",
            "text": {
              "encoding": "base64",
              "contentType": "plain/text",
              "content": "..."
            }
          }
        },
        {
          "license": {
            "id": "MIT",
            "text": {
              "encoding": "base64",
              "contentType": "plain/text",
              "content": "..."
            }
          }
        }
      ],
```

Or did I miss something?
