### ISSUE TITLE
`license_finding_curations` with `source_artifact_url` do not get applied for packages

### ISSUE THREAD

**Issue by pepper-jk** [oss-review-toolkit/ort#7213]
Referencing a package via `source_artifact_url` in `package_configurations` results in `licensing_finding_curations` not to being applied, especially if defined in the `.ort.yml`.
It works with `vcs` information and fails with `source_artifact_url`.

I created a reproducible example [here](https://github.com/pepper-jk/ort_pypi_resolution_test/tree/pkg_curations) [1], which includes a `.ort.yml` with `package_configurations` that don't work and **out-commented** ones with `vcs` that do.
I even added `license_finding_curations` with explicit artifact paths and "project" `curations` to be sure, I did not mess up.

(Mapping `TCL` to `Vim` does not make any sense. It is just meant to be easily visible in the `evaluation-results.yml` and the `web-app-report`.)

### Additional Context:
Last week I complained about custom licenses not working for (package) curations.
After a lot of trail and error, I finally figured out that using `vcs` instead of `source_artifact_url` to reference the package did the trick. [2]

Now I have a different project where I have a package that does not have any `vcs` but only a source artifact. So now I need the `source_artifact_url` to actually work for `license_finding_curations` in `package_configurations`.

Upon feedback from @fviernau in Slack [3], I also tried creating a catch all curation, which also did not get applied:
```
package_configurations:
- id: "PyPI::pillow:9.2.0"
  source_artifact_url: "https://files.pythonhosted.org/packages/8c/92/2975b464d9926dc667020ed1abfa6276e68c3571dcb77e43347e15ee9eed/Pillow-9.2.0.tar.gz"
  license_finding_curations:
  - path: "**/*"
    reason: "INCORRECT"
    comment: "test curation"
    concluded_license: "Vim"
```

We then decided to open this issue.

[1] https://github.com/pepper-jk/ort_pypi_resolution_test/tree/pkg_curations
[2] https://ort-talk.slack.com/archives/C9NNJ54B1/p1687263011355689?thread_ts=1686827765.465319&cid=C9NNJ54B1
[3] https://ort-talk.slack.com/archives/C9NNJ54B1/p1687866704032119?thread_ts=1687865984.351029&cid=C9NNJ54B1
