### ISSUE TITLE
Overriding vulnerabilities seems to be having an issue 

### ISSUE THREAD

**Issue by saaskesaakura345** [oss-review-toolkit/ort#7357]
We have been using ORT for sometime now, but with the latest ORT changes it is observed that the resolutions in the .ort.yml file seems to be ignored for the vulnerabilities. But it is working perfectly fine for rule violations.

Below is the sample .ort.yml file with the resolution details,
**.ort.yml file**
```
resolutions:
  rule_violations:
  - message: ".*PyPI::astroid:2.15.6.*"
    reason: "DYNAMIC_LINKAGE_EXCEPTION"
    comment: "override this violation as we already took approval from OSPO."
    
  vulnerabilities:
  - id: "GHSA-5wv5-4vpf-pj6m"
    reason: "INVALID_MATCH_VULNERABILITY"
    comment: "This vulnerability is not affecting my application."
```
Also attached is the result from evaluation-result.json where we can see that the local configurations have been picked up but in the resolution only rule violations is taken for consideration.
![image](https://github.com/oss-review-toolkit/ort/assets/128026849/9bed9c71-7a81-4dda-bf90-cb1f79d7fbf9)
![image](https://github.com/oss-review-toolkit/ort/assets/128026849/309a46bd-5f5b-464c-98f7-29e21012661b)
