### ISSUE TITLE
Exclusion config not working for gradle during ort analyze when using GradleInspector in ort analze

### ISSUE THREAD

**Issue by dineshr93** [oss-review-toolkit/ort#7483]
Hi 

In continuation of comment
https://github.com/oss-review-toolkit/ort/issues/7479#issuecomment-1711387028 , I observed that the use of GradleInspector during analyze

`ort -P ort.analyzer.enabledPackageManagers=GradleInspector analyze -i . -o . -f JSON`

.ort.yml
```
excludes:
  scopes:
  - pattern: "test.*"
    reason: "TEST_DEPENDENCY_OF"
    comment: "Packages for testing only."
  - pattern: "debug.*"
    reason: "TEST_DEPENDENCY_OF"
    comment: "Packages for testing only."
  - pattern: "jacoco.*"
    reason: "TEST_DEPENDENCY_OF"
    comment: "Packages for testing only."
  - pattern: "releaseAnnotation.*"
    reason: "TEST_DEPENDENCY_OF"
    comment: "Packages for testing only."
  - pattern: "releaseUnitTest.*"
    reason: "TEST_DEPENDENCY_OF"
    comment: "Packages for testing only."
```

But I can still see the scopes in **analyzer-result.json**

![image](https://github.com/oss-review-toolkit/ort/assets/4498415/3fb36141-d904-4807-8dfd-715ce5840ced)

Is the scope exclusion in .ort.yml is not for **GradleInspector** analyze?
