### ISSUE TITLE
Analyzer: Git downloader does not use latest commit when revision is not fixed

### ISSUE THREAD

**Issue by nnobelis** [oss-review-toolkit/ort#7725]
One of our customers wants to run the Analyzer on the `master` branch of his repository.

When the run has finished :
```
vcs_processed:
    type: "Git"
    url: "https://XXX.git"
    revision: "3f3c85c3c662aad724536c4a64e7588e93c9ab0c"
    path: ""
```
This revision is not the latest commit from `master`, this is some old commit from 6 months ago !

I have seen that https://github.com/oss-review-toolkit/ort/pull/7556 introduced a `FETCH_HEAD` mechanism for non fixed revisions.
I have also found that JGit _may_ not be setting `FETCH_HEAD` properly: https://stackoverflow.com/questions/24682310/fetching-with-jgit-doesnt-show-the-last-commit

Could we have an issue here ?
I don't know what I could give for extra information but I would like @mnonnenmacher opinion on this.
