### ISSUE TITLE
Criticality rating is to optimistic

### ISSUE THREAD

**Issue by Ragamuffin85** [oss-review-toolkit/ort#7742]
Hi ORT community,

I was just struggling with with one of my created WebAppReports - In the report the vulnerabilty CVE-2023-2976 is shown with the criticality of MEDIUM.
![image](https://github.com/oss-review-toolkit/ort/assets/843933/bb4520bc-eebb-46a8-bff2-61802a1b1fc6)

I checked all the linked references and found the NIST rating in there (https://nvd.nist.gov/vuln/detail/CVE-2023-2976 )

The NIST rating itself shows two scores
1. NIST: BaseScore: 7.1(HIGH)
2. CNA: BaseScore: 5.5 (Medium)

I'd expect that the report would show me the worst case and therefor I wanted to ask how the decision is taken which score is applied in the report - To be on the save side a more conservative approach, which aims for the highest criticality, could help.

**Comment by sschuberth** [comment]
Thanks for the report @Ragamuffin85. Could you please share (excerpts of) your raw ORT advisor result, so we can have a look which scores are being reported? At the example of a YAML report, I'm interested in a section that looks similar to this:

```
    advisor_results:
      PyPI::flask:2.2.3:
      - advisor:
          name: "OssIndex"
          capabilities:
          - "VULNERABILITIES"
        summary:
          start_time: "2023-02-27T10:47:39.903421900Z"
          end_time: "2023-02-27T10:47:41.258589300Z"
        defects: []
        vulnerabilities:
        - id: "sonatype-2020-0201"
          summary: "1 vulnerability found"
          description: "1 non-CVE vulnerability found. To see more details, please\
            \ create a free account at https://ossindex.sonatype.org/ and request\
            \ for this information using your registered account"
          references:
          - url: "https://ossindex.sonatype.org/vulnerability/sonatype-2020-0201"
            scoring_system: "CVSS:3.1"
            severity: "4.8"
```

**Comment by Ragamuffin85** [comment]
Hi @sschuberth,

thanks for taking care :-)!

Please find attached the excerpts for the mentioned CVE

```
 - id: "CVE-2023-2976"
          references:
          - url: "https://github.com/google/guava/commit/feb83a1c8fd2e7670b244d5afd23cba5aca43284"
            scoring_system: null
            severity: null
          - url: "https://github.com/google/guava/issues/2575"
            scoring_system: null
            severity: null
          - url: "https://github.com/google/guava/issues/6532"
            scoring_system: null
            severity: null
          - url: "https://github.com/google/guava/releases/tag/v32.0.0"
            scoring_system: null
            severity: null
          - url: "https://security.netapp.com/advisory/ntap-20230818-0008/"
            scoring_system: null
            severity: null
          - url: "https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1038979"
            scoring_system: null
            severity: null
          - url: "https://nvd.nist.gov/vuln/detail/CVE-2023-2976"
            scoring_system: null
            severity: null
          - url: "https://github.com/advisories/GHSA-7g45-4rm6-3mm3"
            scoring_system: "cvssv3.1_qr"
            severity: "MEDIUM"
```

It looks like, as only the last entry from github advisories contained any severity-results.
the one from NIST returned with `null` :-(

**Comment by sschuberth** [comment]
> If you need any additional information, please let me know

Could you please also include the part that says which advisor(s) have been used? I assume it was VulnerableCode?

**Comment by Ragamuffin85** [comment]
Sorry, my bad :-)
I'm quite new to this complex environment and since there are some internals in the advisor.yml I don't wanted to share to many information ;-)

```
    advisor_results:
      Maven:com.google.guava:guava:19.0:
      - advisor:
          name: "VulnerableCode"
          capabilities:
          - "VULNERABILITIES"
        summary:
          start_time: "2023-10-26T06:14:51.591670Z"
          end_time: "2023-10-26T06:14:54.198678Z"
        defects: []
        vulnerabilities:
...
        - id: "CVE-2023-2976"
          references:
          - url: "https://github.com/google/guava/commit/feb83a1c8fd2e7670b244d5afd23cba5aca43284"
            scoring_system: null
            severity: null
          - url: "https://github.com/google/guava/issues/2575"
            scoring_system: null
            severity: null
          - url: "https://github.com/google/guava/issues/6532"
            scoring_system: null
            severity: null
          - url: "https://github.com/google/guava/releases/tag/v32.0.0"
            scoring_system: null
            severity: null
          - url: "https://security.netapp.com/advisory/ntap-20230818-0008/"
            scoring_system: null
            severity: null
          - url: "https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1038979"
            scoring_system: null
            severity: null
          - url: "https://nvd.nist.gov/vuln/detail/CVE-2023-2976"
            scoring_system: null
            severity: null
          - url: "https://github.com/advisories/GHSA-7g45-4rm6-3mm3"
            scoring_system: "cvssv3.1_qr"
            severity: "MEDIUM"
```

Whereas the advisor `VulnerableCode` points towards an internal adress

**Comment by sschuberth** [comment]
> Whereas the advisor `VulnerableCode` points towards an internal adress

Which version of VulnerableCode are you hosting internally? I'm asking because there was a change in version 30.0.0 that we did not properly catch up with until https://github.com/oss-review-toolkit/ort/pull/7765. When using a fairly recent version of VulnerableCode plus a brand new ORT that includes the linked PR, this should not happen anymore, as the WebApp report is supposed to already use the "worst" severity for the icon. Could you check on that?

**Comment by Ragamuffin85** [comment]
Hi @sschuberth,

I aligned with the colleagues to gather the necessary information.

The version if "VulnerableCode" that we're using is 32.0.0

This morning a new build was deployed with the mentioned PR in it.

But it seems as the problem still persists.

Please find attached the "new" advisor_results

```
  results:
    advisor_results:
      Maven:com.google.guava:guava:25.0-jre:
      - advisor:
          name: "VulnerableCode"
          capabilities:
          - "VULNERABILITIES"
        summary:
          start_time: "2023-11-02T08:29:12.950584Z"
          end_time: "2023-11-02T08:29:16.656203Z"
        defects: []
        vulnerabilities:
        - id: "CVE-2023-2976"
          references:
          - url: "https://github.com/google/guava/commit/feb83a1c8fd2e7670b244d5afd23cba5aca43284"
            scoring_system: null
            severity: null
            severity_rating: "UNKNOWN"
          - url: "https://github.com/google/guava/issues/2575"
            scoring_system: null
            severity: null
            severity_rating: "UNKNOWN"
          - url: "https://github.com/google/guava/issues/6532"
            scoring_system: null
            severity: null
            severity_rating: "UNKNOWN"
          - url: "https://github.com/google/guava/releases/tag/v32.0.0"
            scoring_system: null
            severity: null
            severity_rating: "UNKNOWN"
          - url: "https://security.netapp.com/advisory/ntap-20230818-0008/"
            scoring_system: null
            severity: null
            severity_rating: "UNKNOWN"
          - url: "https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1038979"
            scoring_system: null
            severity: null
            severity_rating: "UNKNOWN"
          - url: "https://nvd.nist.gov/vuln/detail/CVE-2023-2976"
            scoring_system: null
            severity: null
            severity_rating: "UNKNOWN"
          - url: "https://github.com/advisories/GHSA-7g45-4rm6-3mm3"
            scoring_system: "cvssv3.1_qr"
            severity: "MEDIUM"
            severity_rating: "MEDIUM"
```

TBH there's not that much of a difference :-)

P.S. meanwhile we upgraded the dependency, but the vulnerability is still in there ;-)
