### ISSUE TITLE
Trying to Use `.ort.yml` Repository Configuration for Package Concluded License Finding

### ISSUE THREAD

**Issue by scottschreckengaust** [oss-review-toolkit/ort#7753]
The documenation for [Repository Configuration (.ort.yml)](https://oss-review-toolkit.org/ort/docs/configuration/ort-yml) states:

> [curations](https://oss-review-toolkit.org/ort/docs/configuration/ort-yml#curations) - Overwrite package metadata, set a concluded license or correct license findings.

Yet received the `PACKAGE_CURATION_IN_ORT_YML` error while trying to do so:

> The use of package curations is not allowed in the *.ort.yml file.

----
Using Ort version 4.0.0 here is the recommendation for the `NO_LICENSE_IN_DEPENDENCY` error:
```
{
      "rule" : "NO_LICENSE_IN_DEPENDENCY",
      "pkg" : "PyPI::numpy:1.26.1",
      "license" : null,
      "license_source" : null,
      "severity" : "ERROR",
      "message" : "No license information is available for dependency 'PyPI::numpy:1.26.1'.",
      "how_to_fix" : "If the dependency indeed is unlicensed, it must not be used. Otherwise, please conclude the appropriate license with a package curation."
}
```

Here is the repository configuration `.ort.yml` attempting to fix that received the `PACKAGE_CURATION_IN_ORT_YML`:
```
---
curations:  
  - id: "PyPI::numpy:1.26.1"
    curations:
      comment: "The https://github.com/numpy/numpy/blob/v1.26.1/LICENSE.txt, as a permissive license similar to the BSD 2-Clause License, but with a 3rd clause that prohibits others from using the name of the copyright holder or its contributors to promote derived products without written consent."
      concluded_license: "BSD-3-Clause"
```

**Comment by sschuberth** [comment]
> The use of package curations is not allowed in the *.ort.yml file.

This is meaning to tell you that the feature is "disabled by policy", i.e. you need to enable it in the *global* ORT configuration before ORT user can make use of it in their project repositories, see

https://github.com/oss-review-toolkit/ort/blob/6bb8315a9257864e88d6cc8ae7fe7f6099dbbb0c/model/src/main/resources/reference.yml#L32

**Comment by sschuberth** [comment]
I've clarified this in the docs: https://github.com/oss-review-toolkit/ort/pull/7754

**Comment by sschuberth** [comment]
Improved docs are now live at https://oss-review-toolkit.org/ort/docs/configuration/ort-yml#curations. Feel free to reopen is this does not answer your question @scottschreckengaust.

**Comment by scottschreckengaust** [comment]
Same results, I must be missing something:

> The use of package curations is not allowed in the *.ort.yml file.

I setup a temporary sample repository https://github.com/scottschreckengaust/orter as an attempt to set the `enableRepositoryPackageCurations` using the GitHub Action https://github.com/oss-review-toolkit/ort-ci-github-action with a repository `.ort.yml` file? 

I have reviewed https://github.com/oss-review-toolkit/ort-ci-github-action/blob/main/action.yml and documentation https://oss-review-toolkit.org/ort/docs/configuration/ort-yml#curations and need help still.

Here is a successful run with the artifact report showing the `NO_LICENSE_IN_DEPENDENCY`:
* https://github.com/scottschreckengaust/orter/actions/runs/6778313826

This run shows the `PACKAGE_CURATION_IN_ORT_YML` when attempting to fix with an included `.ort.yml`:
* https://github.com/scottschreckengaust/orter/actions/runs/6778545082


Here is the configuration of the repository's three files:

1) A `requirements.txt` to trigger the `NO_LICENSE_IN_DEPENDENCY` finding:
```requirements.txt
numpy==1.26.1
```

2) A GitHub Workflow `.github/workflows/ort.yml`:
```.github/workflows/ort.yml

---
name: ort-toolkit
on:
  push:
    branches:
      - main
  workflow_dispatch: {}
jobs:
  ort:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Run GitHub Action for ORT
        uses: oss-review-toolkit/ort-ci-github-action@v1
        with:
          ort-cli-args: '-P ort.forceOverwrite=true -P ort.enableRepositoryPackageCurations=true --stacktrace'
```

3) The repository configuration `.ort.yml`:
```.ort.yml
---
curations:
  packages:
  - id: "PyPI::numpy:1.26.1"
    curations:
      comment: "The https://github.com/numpy/numpy/blob/v1.26.1/LICENSE.txt, as a permissive license similar to the BSD 2-Clause License, but with a 3rd clause that prohibits others from using the name of the copyright holder or its contributors to promote derived products without written consent."
      concluded_license: "BSD-3-Clause"
```

**Comment by sschuberth** [comment]
[This line](https://github.com/scottschreckengaust/orter/actions/runs/6778545082/job/18424184695#step:3:1274) actually indicates that the curation has been applied, but there seems to be some bugs in the way the GitHub action calls ORT. It will take me some time to look into this as I'm currently traveling.

**Comment by scottschreckengaust** [comment]
I re-ran the job with debug logging here:
https://github.com/scottschreckengaust/orter/actions/runs/6778545082/job/18447223666

**Comment by scottschreckengaust** [comment]
> [This line](https://github.com/scottschreckengaust/orter/actions/runs/6778545082/job/18424184695#step:3:1274) actually indicates that the curation has been applied, but there seems to be some bugs in the way the GitHub action calls ORT. It will take me some time to look into this as I'm currently traveling.

Yes:
`Applied 1 curation(s) from 1 of 3 provider(s).`

**Comment by scottschreckengaust** [comment]
@sschuberth The analyzer seems to pick up the `.ort.yml`, it is the evaluator which signals an error when local curations or configurations are used https://github.com/oss-review-toolkit/ort-config/blob/ae41944655466de6f63875a6b55ea0d4ccc19780/evaluator.rules.kts#L1370-L1386

I have a PR for changing the error -> warning https://github.com/oss-review-toolkit/ort-config/pull/141

**Comment by sschuberth** [comment]
> it is the evaluator which signals an error when local curations or configurations are used

Good finding, I was confused by this myself.

**Comment by scottschreckengaust** [comment]
@sschuberth There is still the issue in reporting when the package curations and now added configurations switches are set to `true`. Is there a conditional switch warranted in the evaluator?

https://github.com/oss-review-toolkit/ort/blob/6ce0978ecf1b92bb5cfa58488b546be5dbc2b726/plugins/commands/evaluator/src/main/kotlin/EvaluatorCommand.kt#L263?

Updated the GitHub action because "@v1" failing, https://github.com/oss-review-toolkit/ort-ci-github-action/issues/28, so pinned to a commit hash and added the second switch to enable repository configurations also for completion mapped the license:

`.ort.yml`
```
---
curations:
  packages:
  - id: "PyPI::numpy:1.26.1"
    curations:
      comment: "The https://github.com/numpy/numpy/blob/v1.26.1/LICENSE.txt, as a permissive license similar to the BSD 2-Clause License, but with a 3rd clause that prohibits others from using the name of the copyright holder or its contributors to promote derived products without written consent."
      declared_license_mapping:
        "BSD License": "BSD-3-Clause"
      concluded_license: "BSD-3-Clause"
```

`.github/workflows/orter.yml`
```
---
name: ort-toolkit
on:
  push:
    branches:
      - main
  workflow_dispatch: {}
jobs:
  ort:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Run GitHub Action for ORT
        uses: oss-review-toolkit/ort-ci-github-action@7f23c1f8d169dad430e41df223d3b8409c7a156e
        with:
          ort-cli-args: '-P ort.forceOverwrite=true -P ort.enableRepositoryPackageConfigurations=true -P ort.enableRepositoryPackageCurations=true --stacktrace'
```
