### ISSUE TITLE
NPM package with dot confused with another package

### ISSUE THREAD

**Issue by timo-HERE** [oss-review-toolkit/ort#8101]
Seems like ORT is considering these two packages as the same (pkg:npm/object-assign@4.1.1):
* https://github.com/ljharb/object.assign/blob/v4.1.1/package.json#L2
* https://github.com/sindresorhus/object-assign/blob/v4.1.1/package.json#L2

```
Exception in thread "main" java.lang.IllegalArgumentException: Unable to create the AnalyzerResult as it contains packages and projects with the same ids: 
[[
Package(id=Identifier(type=NPM, namespace=, name=object-assign, version=4.1.1), 
purl=pkg:npm/object-assign@4.1.1, cpe=null, authors=[Sindre Sorhus], declaredLicenses=[MIT], declaredLicensesProcessed=ProcessedDeclaredLicense(spdxExpression=MIT, mapped={}, unmapped=[]), concludedLicense=null, description=ES2015 `Object.assign()` ponyfill, 
homepageUrl=https://github.com/ljharb/object.assign#readme, 
binaryArtifact=RemoteArtifact(url=, hash=Hash(value=, algorithm=)),
sourceArtifact=RemoteArtifact(url=https://registry.npmjs.org/object.assign/-/object.assign-4.1.1.tgz, hash=Hash(value=303867a666cdd41936ecdedfb1f8f3e32a478cdd, algorithm=SHA-1)), 
vcs=VcsInfo(type=Git, url=git://github.com/ljharb/object.assign.git, revision=af0f4e870637b1883b3c99d3f66b1f0bd3a35ca8, path=), 
vcsProcessed=VcsInfo(type=Git, url=https://github.com/ljharb/object.assign.git, revision=af0f4e870637b1883b3c99d3f66b1f0bd3a35ca8, path=), isMetadataOnly=false, isModified=false), 

Package(id=Identifier(type=NPM, namespace=, name=object-assign, version=4.1.1), 
purl=pkg:npm/object-assign@4.1.1, cpe=null, authors=[Sindre Sorhus], declaredLicenses=[MIT], declaredLicensesProcessed=ProcessedDeclaredLicense(spdxExpression=MIT, mapped={}, unmapped=[]), concludedLicense=null, description=ES2015 `Object.assign()` ponyfill, 
homepageUrl=https://github.com/sindresorhus/object-assign#readme, 
binaryArtifact=RemoteArtifact(url=, hash=Hash(value=, algorithm=)),
sourceArtifact=RemoteArtifact(url=https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz, hash=Hash(value=2109adc7965887cfc05cbbd442cac8bfbb360863, algorithm=SHA-1)), 
vcs=VcsInfo(type=Git, url=git+https://github.com/sindresorhus/object-assign.git, revision=a89774b252c91612203876984bbd6addbe3b5a0e, path=), 
vcsProcessed=VcsInfo(type=Git, url=https://github.com/sindresorhus/object-assign.git, revision=a89774b252c91612203876984bbd6addbe3b5a0e, path=), isMetadataOnly=false, isModified=false)
]]
```

**Comment by sschuberth** [comment]
I cannot reproduce the problem. For testing, I've created a `package.json` that contains

```
  "dependencies": {
    "object.assign": "4.1.1",
    "object-assign": "4.1.1"
  }
```

and the analyzer result correctly contains

```
    - id: "NPM::object-assign:4.1.1"
      purl: "pkg:npm/object-assign@4.1.1"
      authors:
      - "Sindre Sorhus"
      declared_licenses:
      - "MIT"
      declared_licenses_processed:
        spdx_expression: "MIT"
      description: "ES2015 `Object.assign()` ponyfill"
      homepage_url: "https://github.com/sindresorhus/object-assign#readme"
      binary_artifact:
        url: ""
        hash:
          value: ""
          algorithm: ""
      source_artifact:
        url: "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz"
        hash:
          value: "2109adc7965887cfc05cbbd442cac8bfbb360863"
          algorithm: "SHA-1"
      vcs:
        type: "Git"
        url: "git+https://github.com/sindresorhus/object-assign.git"
        revision: "a89774b252c91612203876984bbd6addbe3b5a0e"
        path: ""
      vcs_processed:
        type: "Git"
        url: "https://github.com/sindresorhus/object-assign.git"
        revision: "a89774b252c91612203876984bbd6addbe3b5a0e"
        path: ""
```

and

```
    - id: "NPM::object.assign:4.1.1"
      purl: "pkg:npm/object.assign@4.1.1"
      authors:
      - "Jordan Harband"
      declared_licenses:
      - "MIT"
      declared_licenses_processed:
        spdx_expression: "MIT"
      description: "ES6 spec-compliant Object.assign shim. From https://github.com/es-shims/es6-shim"
      homepage_url: "https://github.com/ljharb/object.assign#readme"
      binary_artifact:
        url: ""
        hash:
          value: ""
          algorithm: ""
      source_artifact:
        url: "https://registry.npmjs.org/object.assign/-/object.assign-4.1.1.tgz"
        hash:
          value: "303867a666cdd41936ecdedfb1f8f3e32a478cdd"
          algorithm: "SHA-1"
      vcs:
        type: "Git"
        url: "git://github.com/ljharb/object.assign.git"
        revision: "af0f4e870637b1883b3c99d3f66b1f0bd3a35ca8"
        path: ""
      vcs_processed:
        type: "Git"
        url: "https://github.com/ljharb/object.assign.git"
        revision: "af0f4e870637b1883b3c99d3f66b1f0bd3a35ca8"
        path: ""
```

Please provide a valid test project to reproduce the issue.
