### ISSUE TITLE
Better source artifact comparison?

### ISSUE THREAD

**Issue by timo-HERE** [oss-review-toolkit/ort#8127]
I have a case where I think ORT considers these two packages as two different ones:
```
 name=js-yaml,
 version=3.13.1,
 purl=pkg:npm/js-yaml@3.13.1,
 sourceArtifact=RemoteArtifact(url=https://registry.npmjs.org/js-yaml/-/js-yaml-3.13.1.tgz,
 hash=Hash(value=aff151b30bfdfa8e49e05da22e7415e9dfa37847,
 url=git+https://github.com/nodeca/js-yaml.git,
 revision=665aadda42349dcae869f12040d9b10ef18d12da,

 name=js-yaml,
 version=3.13.1,
 purl=pkg:npm/js-yaml@3.13.1,
 sourceArtifact=RemoteArtifact(url=https://artifactory.local/artifactory/js-yaml/-/js-yaml-3.13.1.tgz,
 hash=Hash(value=aff151b30bfdfa8e49e05da22e7415e9dfa37847,
 url=https://github.com/nodeca/js-yaml.git,
 revision=665aadda42349dcae869f12040d9b10ef18d12da,
```
Is there a way to configure ORT to consider these two source artifact URLs the same since they have same filename and hash?

**Comment by sschuberth** [comment]
In which part of ORT would you like ORT to treat these as equal? Like, do you get these entries from a single analyzer run, but want only one of the entries? Or are you comparing different analyzer runs?

And how exactly should treating them the same work? Like, if consolidating these entries to one, to which one should be consolidated in general terms?

**Comment by timo-HERE** [comment]
@sschuberth, these entires were for from single analyzer run, but in order to cache results effectively, these entries should be seen as one between runs.

If the filename in `sourceArtifact` (js-yaml-3.13.1.tgz) and the `hash` matches, why the download server would matter?

**Comment by sschuberth** [comment]
> why the download server would matter?

So you're proposing to download such artifacts only *once* for scanning, from an arbitrary location of those locations that provide the same by (by name and hash)?

**Comment by timo-HERE** [comment]
Yes, correct.

**Comment by timo-HERE** [comment]
@sschuberth, In addition I just realised that ORT probably requires separate package configurations for each download location. Would be great to fix this at the same time.

```yaml
id: "NPM::js-yaml:3.13.1"
source_artifact_url: "https://registry.npmjs.org/js-yaml/-/js-yaml-3.13.1.tgz"
path_excludes:
- pattern: "package/*.md"
  reason: "DOCUMENTATION_OF"
  comment: "Documentation within the package"
```

```yaml
id: "NPM::js-yaml:3.13.1"
source_artifact_url: "https://artifactory.local/artifactory/js-yaml/-/js-yaml-3.13.1.tgz"
path_excludes:
- pattern: "package/*.md"
  reason: "DOCUMENTATION_OF"
  comment: "Documentation within the package"
```

**Comment by sschuberth** [comment]
> Would be great to fix this at the same time.

That's a completely different area of code, though. Anyway, contributions are welcome 😉

**Comment by timo-HERE** [comment]
@sschuberth, I created a new issue for that: https://github.com/oss-review-toolkit/ort/issues/8236

I could also see an alternative, less disruptive solution to the problem. 

Most of the source and binary artifacts have a primary public download location. Kind of "ground zero".
This whole thing is caused from a fact that local caches are used for those public repositories.
ORT could have a global "URL replace function" as part of ORT configuration which is used for all remote artifacts.
```yaml
ort:
  remoteArtifactURLs:
  - replace: "http://"
    with: "https://"
  - replace: "https://registry.npmjs.org/"
    with: "https://artifactory.local/npm-virtual-repository/"
  - replace: "https://repo.maven.apache.org/maven2/"
    with: "https://artifactory.local/maven-cache/" 
```

The result would be that ORT would use those local caches or proxies and deduplication happens as a side product.
