### ISSUE TITLE
Downloader command is missing provenance resolution

### ISSUE THREAD

**Issue by nnobelis** [oss-review-toolkit/ort#8130]
One of our customer complained about unwanted source code in the bundles generated by the `DownloaderCommand`:
```
ORT (at least it feels like) at some point changed the source code resolution strategy for packages from looking at mavencentral or similar, to finding the related github project and check everything out, that's in there.

The problem here is, that the github project may contain other projects or build code or test code that is not related or distributed with the original package dependency that we use. This leads to:
-     either ORT not finding sources for commonly used libraries, although source jars are available on mavencentral
-     Licenses are listed for the component, that do not apply, e.g. if test code on github uses GPL, this is reflected as license for the package

In both cases, data curations have to be done.
``` 

After looking at the code and talking with @mnonnenmacher , we realized the `DownloaderCommand` does not use the provenance resolution used by the Downloader during the Scanner phase.
This could lead to some discrepancy where the source code the scanner is working on is not the same code as in the source code bundle.
This should be aligned.

**Comment by sschuberth** [comment]
> strategy for packages from looking at mavencentral or similar, to finding the related github project and check everything out

To me, that actually sounds more like a source code origin configuration topic, and like it could be resolved by simply configuring `sourceCodeOrigins = listOf(SourceCodeOrigin.ARTIFACT, SourceCodeOrigin.VCS)`. I've actually wondered several times now whether we should make that the new default, as source artifacts are more likely to contain only the relevant code.

**Comment by nnobelis** [comment]
@sschuberth  I forgot to say that the customer uses already:
```
sourceCodeOrigins: ['ARTIFACT', 'VCS']
```

**Comment by fviernau** [comment]
> I've actually wondered several times now whether we should make that the new default, as source artifacts are more likely to contain only the relevant code.

I believe that working with `VCS` is more efficient in clearance for multiple reasons.

**Comment by sschuberth** [comment]
Also, the report is for `GradleInspector` only.

**Comment by nnobelis** [comment]
I pushed a test repository that should exhibit the bug:
https://github.com/nnobelis/GradleTest

If you look at ort/analyzer-result.yml created with `ort -P ort.analyzer.enabledPackageManagers=GradleInspector analyze --output-dir=ort -i Module2`, you see that the Junit package has empty source and binary artifacts:
```
packages:
    - id: "Maven:org.junit.jupiter:junit-jupiter:5.9.1"
      purl: "pkg:maven/org.junit.jupiter/junit-jupiter@5.9.1"
      homepage_url: "https://junit.org/junit5/"
      binary_artifact:
        url: ""
        hash:
          value: ""
          algorithm: ""
      source_artifact:
        url: ""
        hash:
          value: ""
          algorithm: ""
```
