### ISSUE TITLE
Use file name and hash for source artifact package configurations.

### ISSUE THREAD

**Issue by timo-HERE** [oss-review-toolkit/ort#8236]
In case same source artifact is downloaded from two different locations, we need to write several identical curations.

```yaml
id: "NPM::js-yaml:3.13.1"
source_artifact_url: "https://registry.npmjs.org/js-yaml/-/js-yaml-3.13.1.tgz"
path_excludes:
- pattern: "package/*.md"
  reason: "DOCUMENTATION_OF"
  comment: "Documentation within the package"
```

```yaml
id: "NPM::js-yaml:3.13.1"
source_artifact_url: "https://artifactory.local/artifactory/js-yaml/-/js-yaml-3.13.1.tgz"
path_excludes:
- pattern: "package/*.md"
  reason: "DOCUMENTATION_OF"
  comment: "Documentation within the package"
```

I would propose that ORT would use source artifact hash and ignore the server and path from source_artifact_url (for backward compatibility), so that we do not need to create same package configurations over and over.

```yaml
id: "NPM::js-yaml:3.13.1"
source_artifact_url: "https://one-of-the-urls-pointing-to/js-yaml-3.13.1.tgz"
source_artifact_hash: "aff151b30bfdfa8e49e05da22e7415e9dfa37847"
path_excludes:
- pattern: "package/*.md"
  reason: "DOCUMENTATION_OF"
  comment: "Documentation within the package"
```
