### ISSUE TITLE
`DEPENDS_ON` does not for to refer to external SPDX documents

### ISSUE THREAD

**Issue by sschuberth** [oss-review-toolkit/ort#8359]
> Yes this works for inline documents when package relations are defined in the root/project document with DEPENDS_ON but it seems this is broken for external documents. I have changed the relations in analyzer/src/funTest/assets/projects/synthetic/spdx/libs/my-lib/package.spdx.yml to

```
relationships:
- spdxElementId: "SPDXRef-Package-my-lib"
  relationshipType: "DEPENDS_ON"
  relatedSpdxElement: "DocumentRef-curl-7.70.0:SPDXRef-Package-curl"
- spdxElementId: "SPDXRef-Package-my-lib"
  relationshipType: "DEPENDS_ON"
  relatedSpdxElement: "DocumentRef-openssl-1.1.1g:SPDXRef-Package-openssl"
- spdxElementId: "SPDXRef-Package-my-lib"
  relationshipType: "DYNAMIC_LINK"
  relatedSpdxElement: "DocumentRef-curl-7.70.0:SPDXRef-Package-curl"

```
and now the test for "retrieve transitive dependencies" fails

_Originally posted by @JSurf in https://github.com/oss-review-toolkit/ort/pull/4844#discussion_r1507168403_

**Comment by JSurf** [comment]
Thanks for creating the issue.
To clarify:
DEPENDS_ON works fine when used in the "main" document but fails when packages are referenced with DEPENDS_ON in an external library document

Background:
We want to generate an aggregated report from multiple modules. For that we want to use ORT to create SPDX documents for every module first, then use one "main project" SPDX document to reference those submodules to generate an aggregated report. 

ORT spdx reporter generates DEPENDS_ON relationships in SPDXs. So in the aggregated report, no packages are found due to this bug. When manually changing the relations in the module SPDX to DEPENDENCY_OF the results contain all packages.

It does not matter if the packages itself are inline in the referenced module SPDX or also referenced from an external SPDX.

**Comment by JSurf** [comment]
It seems the bug is even more simple and has nothing to do with referencing external documents and can be reproduced with a single document.

It seems DEPENDS_ON is only supported when the spdxElementId is the "root" ID (same as documentDescribes). 
For anything nested, it seems only DEPENDENCY_OF is supported.

Taking the packages-inline example as a base (https://github.com/oss-review-toolkit/ort/blob/main/plugins/package-managers/spdx/src/funTest/assets/projects/synthetic/inline-packages/project-xyz.spdx.yml)

The following relationships **do work** (openssl found and listed as apackage):

Original Code:
```
relationships:
- spdxElementId: "SPDXRef-Package-curl"
  relationshipType: "TEST_DEPENDENCY_OF"
  relatedSpdxElement: "SPDXRef-Package-xyz"
- spdxElementId: "SPDXRef-Package-xyz"
  relationshipType: "DEPENDS_ON"
  relatedSpdxElement: "SPDXRef-Package-openssl"
- spdxElementId: "SPDXRef-Package-xyz"
  relationshipType: "DYNAMIC_LINK"
  relatedSpdxElement: "SPDXRef-Package-curl"
- spdxElementId: "SPDXRef-Package-xyz"
  relationshipType: "STATIC_LINK"
  relatedSpdxElement: "SPDXRef-Package-zlib"

```

Make openssl a DEPENDENCY_OF curl:
```
relationships:
- spdxElementId: "SPDXRef-Package-curl"
  relationshipType: "TEST_DEPENDENCY_OF"
  relatedSpdxElement: "SPDXRef-Package-xyz"
- spdxElementId: "SPDXRef-Package-openssl"
  relationshipType: "DEPENDENCY_OF"
  relatedSpdxElement: "SPDXRef-Package-curl"
- spdxElementId: "SPDXRef-Package-xyz"
  relationshipType: "DYNAMIC_LINK"
  relatedSpdxElement: "SPDXRef-Package-curl"
- spdxElementId: "SPDXRef-Package-xyz"
  relationshipType: "STATIC_LINK"
  relatedSpdxElement: "SPDXRef-Package-zlib"

```

The following example **do not** work (openssl not found):

Make curl DEPENDS_ON openssl:
```
relationships:
- spdxElementId: "SPDXRef-Package-curl"
  relationshipType: "TEST_DEPENDENCY_OF"
  relatedSpdxElement: "SPDXRef-Package-xyz"
- spdxElementId: "SPDXRef-Package-curl"
  relationshipType: "DEPENDS_ON"
  relatedSpdxElement: "SPDXRef-Package-openssl"
- spdxElementId: "SPDXRef-Package-xyz"
  relationshipType: "DYNAMIC_LINK"
  relatedSpdxElement: "SPDXRef-Package-curl"
- spdxElementId: "SPDXRef-Package-xyz"
  relationshipType: "STATIC_LINK"
  relatedSpdxElement: "SPDXRef-Package-zlib"

```

Make openssl a RUNTIME_DEPENDENCY_OF curl:
```
relationships:
- spdxElementId: "SPDXRef-Package-curl"
  relationshipType: "TEST_DEPENDENCY_OF"
  relatedSpdxElement: "SPDXRef-Package-xyz"
- spdxElementId: "SPDXRef-Package-openssl"
  relationshipType: "RUNTIME_DEPENDENCY_OF"
  relatedSpdxElement: "SPDXRef-Package-curl"
- spdxElementId: "SPDXRef-Package-xyz"
  relationshipType: "DYNAMIC_LINK"
  relatedSpdxElement: "SPDXRef-Package-curl"
- spdxElementId: "SPDXRef-Package-xyz"
  relationshipType: "STATIC_LINK"
  relatedSpdxElement: "SPDXRef-Package-zlib"

```

I think the issue could be here where DEPENDENCY_OF is hardcoded, but as a pure java developer I have hard time understanding the Kotlin code:

https://github.com/oss-review-toolkit/ort/blob/165c2102e0dea0cec2f60d434b154effb8a5ab84/plugins/package-managers/spdx/src/main/kotlin/SpdxDocumentFile.kt#L424-L440
