### ISSUE TITLE
Curations for direct conan dependency are not being applied (but for transitive dependencies they are working)

### ISSUE THREAD

**Issue by malmor** [oss-review-toolkit/ort#8853]
### Describe the bug

We have some conan dependencies in `conanfile.py` files that specify invalid licenses - so a curation with a `declared_license_mapping` is required to fix these issues. While this is working perfectly fine for transitive dependencies, we can not get it working for direct dependencies.

<details>
  <summary>Conan dependencies</summary>

  ### test/conan/CoAwaitLib/conanfile.py
  ```python
from conans import ConanFile
from conans import tools
import os

class CoAwaitLibConan(ConanFile):
    name        = "CoAwaitLib"
    version     = "2021-01-22"
    license     = "MIT"
    author      = "Copyright (c) 2020 Ludger Sprenker"
    description = "co::await at any point of your code with stackfull coroutines (C++14)"
    homepage    = "https://github.com/mrpi/CoAwaitLib"
    url         = "https://github.com/mrpi/CoAwaitLib"
    git_commit  = "374990809ffb588453c8b9c8ab623d1e04b3ccf0"
    requires    = "boost/1.85.0"

    no_copy_source = True
    
    def source(self):
        cmd_clone = "git clone %s ./%s" % (self.url,self.name)
        cmd_cd = "cd ./%s" % self.name
        cmd_reset = "git reset --hard %s" % self.git_commit
        cmd = "%s && %s && %s" % (cmd_clone,cmd_cd,cmd_reset)
        
        self.run(cmd)

    def package(self):
        self.copy("LICENSE", "licenses")
        self.copy("*.hpp")

    def package_id(self):
        self.info.header_only()

    def package_info(self):
        self.cpp_info.includedirs = ["CoAwaitLib/include"]

# https://docs.conan.io/en/latest/reference/conanfile/methods.html#package-info
  ```

  ### test/conan/range-v3/conanfile.py
  ```python
# Range v3 library
#
#  Copyright Luis Martinez de Bartolome Izquierdo 2016
#
#  Use, modification and distribution is subject to the
#  Boost Software License, Version 1.0. (See accompanying
#  file LICENSE_1_0.txt or copy at
#  http://www.boost.org/LICENSE_1_0.txt)
#
# Project home: https://github.com/ericniebler/range-v3
#

from conans import ConanFile


class Rangev3Conan(ConanFile):
    name = "range-v3"
    version = "0.11.0"
    license = "Boost Software License - Version 1.0 - August 17th, 2003"
    description = "Provides the range library for C++11/14/17."
    url = "https://github.com/ericniebler/range-v3" # test with it!
    git_commit = "4989f3e9ff2efee1852942bb9328ef121369ba02"
    exports = "*"

    def source(self):
        # this will create a liquidpp subfolder, take it into account
        self.run("git clone https://github.com/ericniebler/range-v3.git ./%s && cd ./%s && git reset --hard %s" % (self.name, self.name, self.git_commit))

    def package(self):
        self.copy("*.hpp", src="range-v3/include", dst="include", keep_path=True)
  ```

</details>

<details>
  <summary>Tested curations</summary>

  ### .ort/config/curations/Conan/_/bzip2.yml (working as expected)
  ```yaml
- id: "Conan::bzip2"
    curations:
      comment: >-
        https://sourceware.org/bzip2/ contains bzip2-1.0.6
      declared_license_mapping:
        "bzip2-1.0.8": "bzip2-1.0.6"
  ```

  ### .ort/config/curations/Conan/_/CoAwaitLib.yml (not working)
  ```yaml
- id: "Conan::CoAwaitLib:2021-01-22"
    curations:
      comment: >-
        Just for the sake of testing, let's configure 'Apache-2.0' as the license for this package.
      declared_license_mapping:
        "MIT": "Apache-2.0"
  ```

  ### .ort/config/curations/Conan/_/range-v3.yml (not working)
  ```yaml
- id: "Conan::range-v3:0.11.0"
    curations:
      comment: >-
        https://github.com/ericniebler/range-v3?tab=License-1-ov-file#readme contains Boost Software License - Version 1.0
      concluded_license: "BSL-1.0"
      declared_license_mapping:
        "Boost Software License - Version 1.0 - August 17th, 2003": "BSL-1.0"
  ```

  ### .ort/config/curations/Conan/_/range-v3.yml (without version identifier - still not working)
  ```yaml
- id: "Conan::range-v3"
    curations:
      comment: >-
        https://github.com/ericniebler/range-v3?tab=License-1-ov-file#readme contains Boost Software License - Version 1.0
      concluded_license: "BSL-1.0"
      declared_license_mapping:
        "Boost Software License - Version 1.0 - August 17th, 2003": "BSL-1.0"
  ```

  ### .ort.yml (not working)
  ```yaml
curations:
  packages:
  - id: "Conan::CoAwaitLib:2021-01-22"
    curations:
      comment: >-
        Just for the sake of testing, let's configure 'Apache-2.0' as the license for this package.
      declared_license_mapping:
        "MIT": "Apache-2.0"
  - id: "Conan::range-v3:0.11.0"
    curations:
      comment: >-
        https://github.com/ericniebler/range-v3?tab=License-1-ov-file#readme contains Boost Software License - Version 1.0
      declared_license_mapping:
        "Boost Software License - Version 1.0 - August 17th, 2003": "BSL-1.0"
  ```

</details>

For the transitive dependency `Conan::bzip2` the curation is working:
```
Effective SPDX: bzip2-1.0.6
Declared: bzip2-1.0.8
Declared (SPDX): bzip2-1.0.6
```

For both the direct dependencies `Conan::CoAwaitLib:2021-01-22` and `Conan::range-v3:0.11.0` they are not working:
```
# CoAwaitLib
Declared: MIT
Declared (SPDX): MIT

# range-v3
Declared: Boost Software License - Version 1.0 - August 17th, 2003
Declared (non-SPDX): Boost Software License - Version 1.0 - August 17th, 2003
```

We tested global package curations and repository curations (`range-v3.yml` and `.ort.yml`), tried with and without version matchers and enabled DEBUG logging - but no success in getting the `UNHANDLED_DECLARED_LICENSE` issue fixed.

### To Reproduce

1. Create both `conanfile.py` files locally (see above)
2. Create the curations (either in `.ort.yml` or the default curations directory)
3. Run `ort` (analyze + evaluate + report) on the files

### Expected behavior

The curation should be applied to the package - and the `UNMAPPED_DECLARED_LICENSE` issue resolved.

### Console / log output

```
 ______________________________                                                
/        \_______   \__    ___/ The OSS Review Toolkit, version 22.5.0,        
|    |   | |       _/ |    |    built with JDK 11.0.23+9, running under Java 17
|    |   | |    |   \ |    |    Executing 'evaluate' as 'ort' on Linux         
\________/ |____|___/ |____|    with 8 CPUs and a maximum of 8192 MiB of memory
                                                                               
Environment variables:                                                        
ORT_CONFIG_DIR = /home/ort/.ort/config                                        
ORT_DATA_DIR = /builds/my-group/my-app/.ort                
HOME = /home/ort                                                              
JAVA_HOME = /opt/java/openjdk                                                 
ANDROID_HOME = /opt/android-sdk                                               
                                                                              
Looking for ORT configuration in the following file:
        /home/ort/.ort/config/config.yml
Looking for evaluator-specific configuration in the following files, directories and resources:
        /home/ort/.ort/config/copyright-garbage.yml
        /home/ort/.ort/config/license-classifications.yml
        /home/ort/.ort/config/evaluator.rules.kts
The following 10 rule violations have been found:
WARNING: UNMAPPED_DECLARED_LICENSE - Conan::range-v3:0.11.0 - The declared license 'Boost Software License - Version 1.0 - August 17th, 2003' could not be mapped to a valid license or parsed as an SPDX expression. The license was found in package Conan::range-v3:0.11.0.
```

### Environment

* ORT version: 22.5.0
* Java version: 17
* OS: Linux (Docker)

We are running the public docker image:
```
ghcr.io/oss-review-toolkit/ort:22.5.0@sha256:9796531277a0b1536c36a41461995db3042293b069a7845a268328cb2e6dd6b0
```

*And* specify (relevant parts of) your ORT configuration (`config.yml`):

<details>
  <summary>config.yml</summary>

```
ort:
  addAuthorsToCopyrights: true
  enableRepositoryPackageCurations: true
  enableRepositoryPackageConfigurations: true

  # Based on https://github.com/oss-review-toolkit/ort/blob/21c260ed10433e1abd4cfe3145409950467aaa30/utils/common/src/main/kotlin/EnvironmentVariableFilter.kt
  deniedProcessEnvironmentVariablesSubstrings:
    # Default
    - KEY
    - PASS
    - SECRET
    - TOKEN
    - USER
  allowedProcessEnvironmentVariableNames:
    # Default
    - CARGO_HTTP_USER_AGENT
    - COMPOSER_ALLOW_SUPERUSER
    - CONAN_LOGIN_ENCRYPTION_KEY
    - CONAN_LOGIN_USERNAME
    - CONAN_PASSWORD
    - CONAN_USERNAME
    - CONAN_USER_HOME
    - CONAN_USER_HOME_SHORT
    - DOTNET_CLI_CONTEXT_ANSI_PASS_THRU
    - GIT_ASKPASS
    - GIT_HTTP_USER_AGENT
    - GRADLE_USER_HOME
    - HACKAGE_USERNAME
    - HACKAGE_PASSWORD
    - HACKAGE_KEY
    - PWD
    - USER
    - USERPROFILE
  analyzer:
    allowDynamicVersions: true

    package_managers:
      NuGet:
        options:
          nugetConfigFile: "${NUGET_CONFIG_DIR}/nuget.config"

  scanner:
    skipConcluded: true

    archive:
      enabled: true

      postgresStorage:
        connection:
          url: 'jdbc:postgresql://postgres.company.local:5432/postgres'
          schema: public
          username: ${POSTGRES_USERNAME}
          password: ${POSTGRES_PASSWORD}
          sslmode: require

    createMissingArchives: true

    config:
    # A map from scanner plugin types to the plugin configuration.    
      ScanCode:
        options:
          commandLine: ${ORT_SCANCODE_COMMANDLINE}

    storages:
      artifactoryStorage:
        type: "PROVENANCE_BASED"
        backend:
          httpFileStorage:
            url: 'https://artifactory.company.local/artifactory/scan-results/provenance_based'
            headers:
              X-JFrog-Art-Api: ${ARTIFACTORY_API_TOKEN}

    storageReaders: [artifactoryStorage]

    storageWriters: [artifactoryStorage]

    provenanceStorage:
      postgresStorage:
        connection:
          url: 'jdbc:postgresql://postgres.company.local:5432/postgres'
          schema: public
          username: ${POSTGRES_USERNAME}
          password: ${POSTGRES_PASSWORD}
          sslmode: require 
```

</details>
