### ISSUE TITLE
PostgreSQL sslmode in reference file wrong

### ISSUE THREAD

**Issue by georg-eckert-zeiss** [oss-review-toolkit/ort#9142]
### Describe the bug

PostgreSQL SSL mode "require**d**" invalid. Should be "require". See [postgresql doc](https://www.postgresql.org/docs/9.1/libpq-ssl.html)

### To Reproduce

1. Use the reference config which [contains sslmode: required](https://github.com/oss-review-toolkit/ort/blob/0b24c91542e0598e83e7d359914a47d1a82df338/model/src/main/resources/reference.yml#L196)
2. Then run the scan

### Expected behavior

Information is cached in PostgreSQL database. Database can be accessed.

### Console / log output

`PoolInitializationException: Failed to initialize pool: Invalid sslmode value: required`

### Environment

```
 ______________________________                                                
/        \_______   \__    ___/  The OSS Review Toolkit, version 31.0.0,       
|    |   | |       _/ |    |     built with JDK 11.0.24+8, running under Java 2
|    |   | |    |   \ |    |     Executing 'requirements' as 'AzDevOps' on Linu
\________/ |____|___/ |____|     with 4 CPUs and a maximum of 3996 MiB of memor
```

```
    fileListStorage:
      postgresStorage:
        connection:
          url: "jdbc:postgresql://%POSTGRESQL_URL%/%POSTGRESQL_DB%"
          schema: "public"
          username: "%POSTGRESQL_USER%"
          password: "%POSTGRESQL_PW%"
          sslmode: required
```
