### ISSUE TITLE
Package download fails for open-jdk

### ISSUE THREAD

**Issue by cgi-ricardo** [oss-review-toolkit/ort#9489]
### Describe the bug

We provide https://hg.openjdk.org/jdk-updates/jdk9u/archive/1b1226687b89.zip to ORT to download but it fails with:

> IOException: Could not resolve provenance for package 'Unmanaged::open-jdk:9.0.4+12' for source code origins [VCS, ARTIFACT]. Resolution of ARTIFACT failed with: StreamResetException: stream was reset: INTERNAL_ERROR

### To Reproduce

Run ORT with input:

```
    packages:
    - id: "Unmanaged::open-jdk:9.0.4+12"
      purl: ""
      declared_licenses: []
      declared_licenses_processed: {}
      description: ""
      homepage_url: ""
      binary_artifact:
        url: ""
        hash:
          value: ""
          algorithm: ""
      source_artifact:
        url: "https://hg.openjdk.org/jdk-updates/jdk9u/archive/1b1226687b89.zip"
        hash:
          value: ""
          algorithm: ""
      vcs:
        type: ""
        url: ""
        revision: ""
        path: ""
      vcs_processed:
        type: ""
        url: ""
        revision: ""
        path: ""
```

### Expected behavior

ORT should download it and get the output data result

### Console / log output

n/a

### Environment

```
  environment:
    ort_version: "25.1.0"
    build_jdk: "11.0.23+9"
    java_version: "17.0.11"
    os: "Linux"
```
