### ISSUE TITLE
Package curations: In some cases, they authors don't show up in the Disclosure Document

### ISSUE THREAD

**Issue by wkl3nk** [oss-review-toolkit/ort#9599]
Package curations are well described [here](https://oss-review-toolkit.org/ort/docs/configuration/package-curations#curations-basics).
There are situations where one does **not want to scan a package (with scancode)**, but instead give the appropriate license identifier and a list of authors in a curation file.

For this to work, some conditions must be met:

* The respective curation file of the package contains one or more `authors` (which might be prefixed by "Copyright (c) ..."
* It contains a `concluded_license`
* The ORT configuration has scanner option `scanner.skipConcluded: true`
* The ORT configuration has global option  `addAuthorsToCopyrights: true`

### To Reproduce

Steps to reproduce the behaviour:

Step 1: Set the ORT configuration as stated above under "conditions".

Step 2: Set up a simple NPM project, an example package.json could be:

```json
{
  "name": "Some name",
  "version": "0.0.1",
  "description": "Some description",
  "main": "index.js",
  "license": "ISC",
  "repository": {
    "type": "git",
    "url": "some valid url that can be reached"
  },
  "dependencies": {
    "mime": "1.6.0"
  }
}
```
So, just a single dependency to the _mime_ package.

Step 3: Manually trigger the ORT Analyzer

```sh
$ ort analyze -i . -o .
```
This create a result file _analyzer-result.yml_.

Step 4: Tweak the ORT Analyzer result

For simplicity sake, directly tweak this file with a curation for the mime package. Therefore, add the following section to the end of the _analyzer-result.yml_ file:

```
scanner: null
advisor: null
evaluator: null
resolved_configuration:
  package_curations:
    - provider:
        id: "ocaasPackageCurationProvider"
      curations:
        - id: "NPM::mime:1.6.0"
          curations:
            comment: "Test by John Doe"
            authors:
              - "Copyright (c) 2024 John Doe"
            concluded_license: "BSD-2-Clause"
```
You see, we are giving the mime package a different `concluded_license`and added `authors`.

Step 5: Manually trigger the ORT Scanner (scancode)

```sh
$ ort scan -i analyzer-result.yml -o . --skip-excluded
```
This will generate a result file _scan-result.yml_.

Step 6: Manually trigger the generation of reports

```sh
$ ort --info report -i scan-result.yml -o . -f PdfTemplate,WebApp
```
This generates the files _AsciiDoc_disclosure_document.pdf_ and _scan-report-web-app.html_.

### Expected behavior

In the Web App Report, we see for the _mime_ package:

* Authors: Copyright (c) 2024 John Doe
* Licenses -> Concluded SPDX: BSD-2-Clause
* Licenses -> Declared SPDX: MIT

So, yes, we have successfully overwritten the original author(s) and have changed the license from MIT to BSD-2-Clause.

And: You won't see any scan results in files, because the scanner (scancode) did not run for this package. This was intended.
Everything all right for the Web App Report.

In the Disclose Document, we **expect to see**  for the _mime_ package:

Package URL pkg:npm/mime@1.6.0

* has license BSD-2-Clause
* under this license, has "Copyright (c) 2024 John Do

Outcome: BSD-2-Clause license is displayed correctly, but **the copyright statement is missing**.

### Additional context

This problem only appears when either

* The ORT Analyzer initially did not detect a (declared) license at all
* The curation changes the license from A to B.

### First analysis and possible fix

I did a quite time consuming analysis and will provide a PR how it could be fixed (potentially).
