### ISSUE TITLE
Infer vcs type from curated url automatically

### ISSUE THREAD

**Issue by cz-dev-ge** [oss-review-toolkit/ort#9765]
### What is the existing functionality and how should it be enhanced?

Package curation.

When adding a vcs in a package curation, e.g.

```yml
- id: "NuGet::SkiaSharp"
  curations:
    declared_license_mapping:
      "https://go.microsoft.com/fwlink/?linkid=868514": "MIT"
    vcs:
      url: "https://github.com/mono/SkiaSharp.git"
```

I'll get an empty "type" field in the scan later. ORT could instead detect it automatically from the url.

### What is the use-case for your enhancement?

VCS curation. As a user I want as few curation as possible.
