### ISSUE TITLE
SPDX as package manifest does not work for CONTAINS relationship

### ISSUE THREAD

**Issue by kikofernandez** [oss-review-toolkit/ort#9969]
### Describe the bug

I create a SPDX as a package manifest (https://github.com/spdx/spdx-spec/issues/439) and the relationship `DESCRIBES` does not appear in the `analyzer` output result (because of this, it does not appear either in scanner nor in a final SPDX report)

### To Reproduce

1. Using as example [Elixir language](https://github.com/elixir-lang/elixir/), create the following SPDX package, which simply helps to create some structure for the end result SPDX report.

https://github.com/elixir-lang/elixir/blob/main/project.spdx.yml#L156-L174

2. `./gradlew --no-configuration-cache cli:run --args="analyze -i elixir -o . -f JSON"`
3. Observe how the end result does not contain any relationship. (But if we use the `STATIC_LINK`, the analyzer does create that relationship in the `analyze-result.json`)

### Expected behavior

Expected the contains relation to appear in the `analyze-result.json` and also in the final SPDX report

### Environment

* ORT version: 51
* Java version: 21.0.5
* OS: Ubuntu

*And* specify (relevant parts of) your ORT configuration (`config.yml`):

Elixir [config link](https://github.com/elixir-lang/elixir/blob/main/.ort/config/config.yml), copy-paste below
```
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2021 The Elixir Team

ort:
  enableRepositoryPackageCurations: true

  scanner:
    skipConcluded: false
    includeFilesWithoutFindings: true

  analyzer:
    allowDynamicVersions: true
    enabledPackageManagers: [SpdxDocumentFile]
    skipExcluded: true
```

### Comments

I have observed the same thing for Erlang/OTP and other projects where I tried to create `CONTAINS` relationships.
Another example is this fork of [`jesse`](https://github.com/kikofernandez:jesse:master), and this is the SPDX manifest ([here](https://github.com/for-GET/jesse/compare/master...kikofernandez:jesse:master)):

```
SPDXID: "SPDXRef-DOCUMENT"
spdxVersion: "SPDX-2.2"
creationInfo:
  created: "2025-02-25T10:13:22Z"
  creators:
  - "Organization: Example AB"
  licenseListVersion: "3.26"
name: "jesse-code"
dataLicense: "Apache-2.0"
documentNamespace: "http://spdx.org/spdxdocs/spdx-document-jesse"
documentDescribes:
- "SPDXRef-Project-Jesse"
packages:
- SPDXID: "SPDXRef-Project-Jesse"
  description: "Jesse JSON Schema Validator"
  copyrightText: "Example"
  downloadLocation: "git+https://github.com/kikofernandez/jesse.git"
  filesAnalyzed: true
  homepage: "https://github.com/kikofernandez/jesse.git"
  licenseConcluded: "Apache-2.0"
  licenseDeclared: "Apache-2.0"
  supplier: "Organization: Example"
  originator: "Organization: Example"
  name: "jesse-project"
  versionInfo: "6"
  packageFileName: "./"
- SPDXID: "SPDXRef-Package-jesse-doc"
  description: "Test"
  copyrightText: "Example"
  downloadLocation: "git+https://github.com/kikofernandez/jesse.git#doc"
  filesAnalyzed: true
  supplier: "Organization: Example AB"
  originator: "Organization: Example AB"
  homepage: "https://github.com/for-GET/jesse"
  licenseConcluded: "Apache-2.0"
  licenseDeclared: "Apache-2.0"
  name: "jesse-doc"
  versionInfo: "6"
  packageFileName: "./doc"
- SPDXID: "SPDXRef-Package-jesse-src"
  description: "Test"
  copyrightText: "Example"
  downloadLocation: "git+https://github.com/kikofernandez/jesse.git#src"
  filesAnalyzed: true
  supplier: "Organization: Example AB"
  originator: "Organization: Example AB"
  homepage: "https://github.com/for-GET/jesse"
  licenseConcluded: "Apache-2.0"
  licenseDeclared: "Apache-2.0"
  name: "jesse-src"
  versionInfo: "6"
  packageFileName: "./src"
relationships:
- spdxElementId: "SPDXRef-Project-Jesse"
  relatedSpdxElement: "SPDXRef-Package-jesse-doc"
  relationshipType: "CONTAINS" # Should be CONTAINS, issue with ORT
- spdxElementId: "SPDXRef-Project-Jesse"
  relatedSpdxElement: "SPDXRef-Package-jesse-src"
  relationshipType: "CONTAINS" # Should be CONTAINS, issue with ORT
```

FYI @maennchen

**Comment by kikofernandez** [comment]
I noticed that SPDX as a manifest does not work either for `DOCUMENTATION_OF` and `TEST_OF` relationships

**Comment by fviernau** [comment]
Do I understand correctly that you assume `spdx file  -> analyzer result -> spdx file` should yield the original SPDX file?
(Or at least retains the describes relationships?) 

I believe this assumption is wrong and therefore I remove the "bug" label. Note that SPDX BOM files produced by ORT use the `documentDescribes` property to refer  to the root package representing the project. I believe what could be done, in scope of this ticket, is to check whether this should be refactored, so that a `DESCRIBES` relation is used instead.

**Comment by kikofernandez** [comment]
> (Or at least retains the describes relationships?)
Yes, I thought that if we use a manifest file, the resulting analysis or meta information about the package was going to be kept.
If we declare a `DOCUMENT_OF` relation, it should be preserved. 

> Note that SPDX BOM files produced by ORT use the documentDescribes property to refer to the root package representing the project.
Yes, I thought we have a root project in the `documentDescribes`, and then I can create many small vendor dependencies existing within the root project. For example, in Erlang we could have:
```
SPDXID: "SPDXRef-DOCUMENT"
spdxVersion: "SPDX-2.2"
creationInfo:
  created: "2025-02-25T10:13:22Z"
  creators:
  - "Organization: Ericsson AB"
  licenseListVersion: "3.26"
name: "Erlang/OTP"
dataLicense: "Apache-2.0"
documentNamespace: "http://spdx.org/spdxdocs/spdx-document-erlang-otp"
documentDescribes:
- "SPDXRef-Project-Erlang-OTP"
packages:
  # PROJECT
- SPDXID: "SPDXRef-Project-Erlang-OTP"
  description: "Erlang/OTP programming language"
  supplier: "Organization: Ericsson AB"
  originator: "Organization: Ericsson AB"
  name: "erlang/otp"
  versionInfo: "28.1.1"
  packageFileName: "./"
  ...

  # ERTS package top-level
- SPDXID: "SPDXRef-Package-erts"
  description: "Erlang Runtime System for Erlang/OTP"
  packageFileName: "./erts"
  ...

  # ERTS 3pp vendor
- SPDXID: "SPDXRef-Package-pcre2"
  description: "PCRE vendor library"
  name: "pcre2"
  packageFileName: "./erts/emulator/pcre"
  ...

relationships:
- spdxElementId: "SPDXRef-Project-Erlang-OTP"
  relatedSpdxElement: "SPDXRef-Package-erts"
  relationshipType: "CONTAINS" # Should be CONTAINS, issue with ORT

- spdxElementId: "SPDXRef-Package-pcre2"
  relatedSpdxElement: "SPDXRef-Package-erts"
  relationshipType: "PACKAGE_OF" # Should be CONTAINS, issue with ORT
```

This describes a ErlangOTP project, which CONTAINS the runtime system (ERTS), and a vendor library PCRE2.
For the same reason, using this approach, we can easily categorise `DOCUMENTATION_OF` and `TEST_OF` for documentation living inside packages and tests living inside packages.

Does this make sense? If not, why is `CONTAINS` relationship ok but not the others 😃 ?
